import { editionLicensingErrorCodes } from '../../edition/licensing-error-codes.js';

export interface ErrorCodeDefinition {
  readonly httpStatus: number;
  readonly message: string;
}

const registeredErrorCodes: Record<string, ErrorCodeDefinition> = {
  VALIDATION_FAILED: { httpStatus: 400, message: '请求参数不合法' },
  RESOURCE_NOT_FOUND: { httpStatus: 404, message: '资源不存在' },
  RESOURCE_ALREADY_EXISTS: { httpStatus: 409, message: '资源已存在' },
  RESOURCE_VERSION_CONFLICT: { httpStatus: 409, message: '资源版本冲突' },
  IDEMPOTENCY_CONFLICT: { httpStatus: 409, message: '幂等键冲突' },
  TASK_TYPE_NOT_REGISTERED: { httpStatus: 422, message: '任务类型未注册' },
  TASK_TYPE_DISABLED: { httpStatus: 409, message: '任务类型已停用' },
  TASK_NOT_RETRYABLE: { httpStatus: 409, message: '任务当前状态不允许重试' },
  TASK_STATE_CONFLICT: { httpStatus: 409, message: '任务状态冲突' },
  TASK_LEASE_LOST: { httpStatus: 409, message: '任务租约已失效' },
  TENANT_PARENT_INVALID: { httpStatus: 422, message: '租户父节点无效' },
  TENANT_CYCLE_DETECTED: { httpStatus: 422, message: '租户父子关系不能形成循环' },
  TENANT_NOT_FOUND: { httpStatus: 404, message: '租户不存在或不可用' },
  TENANT_MEMBERSHIP_REQUIRED: { httpStatus: 403, message: '缺少有效租户成员关系' },
  TENANT_CONTEXT_INVALID: { httpStatus: 403, message: '租户上下文无效' },
  TENANT_CONTEXT_STALE: { httpStatus: 409, message: '租户上下文已失效' },
  TENANT_SCOPE_DENIED: { httpStatus: 403, message: '租户范围不允许当前操作' },
  TENANT_PREFLIGHT_FAILED: { httpStatus: 409, message: '多租户启用预检查失败' },
  TENANT_PREFLIGHT_STALE: { httpStatus: 409, message: '多租户预检查批次已过期' },
  TENANT_MODE_CONFLICT: { httpStatus: 409, message: '多租户模式状态冲突' },
  TENANT_MIGRATION_FAILED: { httpStatus: 409, message: '多租户启用或回滚失败' },
  TENANT_ROLLBACK_UNAVAILABLE: { httpStatus: 409, message: '当前没有可用的多租户回滚状态' },
  AUTH_UNAUTHENTICATED: { httpStatus: 401, message: '未认证' },
  AUTH_FORBIDDEN: { httpStatus: 403, message: '无权限' },
  SYSTEM_INTERNAL_ERROR: { httpStatus: 500, message: '系统内部错误' },
  CERT_PARSE_FAILED: { httpStatus: 422, message: '证书解析失败' },
  CERT_PRIVATE_KEY_MISSING: { httpStatus: 422, message: '缺少私钥' },
  CERT_PRIVATE_KEY_MISMATCH: { httpStatus: 422, message: '私钥与证书不匹配' },
  CERT_FORMAT_UNSUPPORTED: { httpStatus: 422, message: '证书格式不支持' },
  CERT_DUPLICATE_VERSION: { httpStatus: 409, message: '重复证书版本' },
  CERT_EXPORT_FORMAT_INVALID: { httpStatus: 422, message: '证书导出格式无效' },
  CERT_EXPORT_FAILED: { httpStatus: 422, message: '证书导出失败' },
  CERT_PRIVATE_KEY_REQUIRED: { httpStatus: 422, message: '目标格式需要私钥' },
  CA_TOPOLOGY_INVALID: { httpStatus: 422, message: 'CA 拓扑无效' },
  CA_RISK_CONFIRMATION_REQUIRED: { httpStatus: 409, message: '需要重新确认 CA 风险' },
  CA_TRUST_DOMAIN_STATE_INVALID: { httpStatus: 409, message: 'CA 信任域状态不允许当前操作' },
  CA_CAPABILITY_UNSUPPORTED: { httpStatus: 422, message: 'CA 能力不支持' },
  CA_OPERATIONS_VIEW_UNSUPPORTED: { httpStatus: 422, message: 'CA 不支持所选运营视图' },
  CA_OPERATIONS_QUERY_INVALID: { httpStatus: 400, message: 'CA 运营查询参数无效' },
  CA_OPERATIONS_CAPABILITY_UNSUPPORTED: { httpStatus: 422, message: 'CA 不支持所需运营能力' },
  CA_OBSERVATION_SOURCE_UNAVAILABLE: { httpStatus: 503, message: 'CA Agent 观测来源不可用' },
  CA_TEMPLATE_MAPPING_CONFLICT: { httpStatus: 409, message: 'CA 模板映射冲突' },
  CA_OPERATION_RESULT_UNKNOWN: { httpStatus: 202, message: 'CA 远程操作结果待确认' },
  CA_KEY_BACKEND_UNAVAILABLE: { httpStatus: 503, message: 'CA 密钥后端不可用' },
  CA_LEDGER_INCONSISTENT: { httpStatus: 409, message: 'CA 签发账本与证书状态不一致' },
  CERTIFICATE_PROMOTION_BLOCKED: { httpStatus: 409, message: '证书版本 Promotion 被阻断' },
  CERTIFICATE_PROFILE_VIOLATION: { httpStatus: 422, message: '证书申请不符合 Profile' },
  CERTIFICATE_TRUST_DOMAIN_MISMATCH: { httpStatus: 422, message: '证书申请、Profile 与 CA 不属于同一信任域' },
  CSR_SIGNATURE_INVALID: { httpStatus: 422, message: 'CSR 签名无效' },
  CSR_ASSET_MISMATCH: { httpStatus: 422, message: 'CSR 与应用资产不匹配' },
  CERTIFICATE_ISSUANCE_PENDING: { httpStatus: 202, message: '证书签发处理中' },
  CERTIFICATE_ISSUANCE_CONFLICT: { httpStatus: 409, message: '证书签发冲突' },
  PUBLIC_KEY_MISMATCH: { httpStatus: 422, message: '公钥不匹配' },
  KEY_REUSE_FORBIDDEN: { httpStatus: 409, message: '禁止跨应用复用私钥' },
  DEFAULT_CERTIFICATE_FORMAT_PROTECTED: { httpStatus: 409, message: '宿主默认证书产物配置文件不允许删除' },
  CERTIFICATE_REVOCATION_UNSUPPORTED: { httpStatus: 422, message: '当前 CA 不支持证书吊销' },
  APPLICATION_CERTIFICATE_POLICY_INVALID: { httpStatus: 422, message: '应用证书供应策略无效' },
  CERTIFICATE_DOMAIN_NOT_MATCHED: { httpStatus: 422, message: '证书 CN/SAN 未覆盖应用域名' },
  ACME_DNS_AUTHORIZATION_REQUIRED: { httpStatus: 422, message: 'ACME DNS 验证授权必填' },
  DEDICATED_CERTIFICATE_OWNERSHIP_CONFLICT: { httpStatus: 409, message: '专属证书归属冲突' },
  CERTIFICATE_ARTIFACT_MODE_MISMATCH: { httpStatus: 422, message: '证书制品模式与密钥归属不匹配' },
  AGENT_LOCAL_KEY_PROOF_INVALID: { httpStatus: 422, message: 'Agent 本机密钥证明无效' },
  CERTIFICATE_OPERATION_UNKNOWN: { httpStatus: 202, message: '证书操作结果未知，等待恢复' },
  UNMANAGED_DEPLOYMENT_CONTEXT_REQUIRED: { httpStatus: 422, message: '无 Agent 目标时必须提供受管部署上下文' },
  CERTIFICATE_ROTATION_CUTOVER_UNVERIFIED: { httpStatus: 409, message: '证书轮换切换尚未完成 TLS 验证' },
  CA_PROVIDER_ACTION_UNBOUND: { httpStatus: 422, message: 'CA Provider 动作尚未绑定' },
  TRUST_DISTRIBUTION_FAILED: { httpStatus: 500, message: '信任链分发失败' },
  ASSET_UNREACHABLE: { httpStatus: 422, message: '资产不可达' },
  BINDING_NOT_MANAGED: { httpStatus: 422, message: '绑定未纳管' },
  CAPABILITY_MISSING: { httpStatus: 422, message: '缺少能力' },
  BROWSER_RUNTIME_UNAVAILABLE: { httpStatus: 503, message: '浏览器运行时不可用' },
  BROWSER_CONTEXT_UNAVAILABLE: { httpStatus: 409, message: '浏览器上下文不可用' },
  TEMPORARY_URL_INVALID: { httpStatus: 403, message: '临时 URL 无效' },
  TEMPORARY_URL_EXPIRED: { httpStatus: 410, message: '临时 URL 已过期' },
  SESSION_NOT_READY: { httpStatus: 409, message: '浏览器会话尚未准备完成' },
  ACQUIRE_ALREADY_RUNNING: { httpStatus: 409, message: '凭据获取已经在运行' },
  WORKFLOW_VERSION_UNAVAILABLE: { httpStatus: 422, message: '凭据获取工作流版本不可用' },
  WORKFLOW_EXECUTION_FAILED: { httpStatus: 422, message: '凭据获取工作流执行失败' },
  CREDENTIAL_OUTPUT_INVALID: { httpStatus: 422, message: '凭据输出不符合合同' },
  CREDENTIAL_VALIDATION_FAILED: { httpStatus: 422, message: '凭据验证失败' },
  CREDENTIAL_EXPIRED: { httpStatus: 422, message: '凭据已过期' },
  CAPABILITY_EXPIRED: { httpStatus: 422, message: '能力检测已过期' },
  DEPLOYMENT_INVALID_STATE: { httpStatus: 409, message: '部署计划状态不允许该操作' },
  DEPLOYMENT_APPROVAL_REQUIRED: { httpStatus: 422, message: '需要审批' },
  DEPLOYMENT_ASSET_CONTEXT_INVALID: { httpStatus: 422, message: '部署资产上下文无效' },
  DEPLOYMENT_INPUT_CONTRACT_INVALID: { httpStatus: 422, message: '部署输入契约无效' },
  EXECUTION_TIMEOUT: { httpStatus: 504, message: '执行超时' },
  EXECUTION_TARGET_UNAVAILABLE: { httpStatus: 503, message: '执行目标不可用' },
  AGENT_OFFLINE: { httpStatus: 503, message: 'Agent 离线' },
  PLUGIN_SIGNATURE_INVALID: { httpStatus: 422, message: '插件签名无效' },
  PLUGIN_PERMISSION_DENIED: { httpStatus: 403, message: '插件权限不足' },
  PLUGIN_CAPABILITY_EXECUTION_FAILED: { httpStatus: 502, message: '插件能力执行失败' },
  PLUGIN_OPERATION_FAILED: { httpStatus: 502, message: '插件操作失败' },
  PLUGIN_REMOTE_ERROR: { httpStatus: 502, message: '插件返回远端错误' },
  PLUGIN_RUNNER_START_FAILED: { httpStatus: 503, message: 'Plugin Runner 启动失败' },
  PLUGIN_RUNNER_HANDSHAKE_FAILED: { httpStatus: 502, message: 'Plugin Runner 握手失败' },
  PLUGIN_RUNNER_TIMEOUT: { httpStatus: 504, message: 'Plugin Runner 执行超时' },
  PLUGIN_RUNNER_CRASHED: { httpStatus: 502, message: 'Plugin Runner 进程异常退出' },
  PLUGIN_HOST_CALL_DENIED: { httpStatus: 403, message: 'Plugin Host API 调用被拒绝' },
  PLUGIN_CONTRACT_INVALID: { httpStatus: 422, message: 'Plugin Runner 合同无效' },
  PLUGIN_OPERATION_UNKNOWN_STATE: { httpStatus: 202, message: '插件外部操作状态未知' },
  PLUGIN_RUNNER_PROTOCOL_VIOLATION: { httpStatus: 502, message: 'Plugin Runner IPC 协议违规' },
  PLUGIN_RUNNER_BUSY: { httpStatus: 409, message: 'Plugin Runner 当前正在执行其他请求' },
  PLUGIN_RUNNER_DRAINING: { httpStatus: 409, message: 'Plugin Runner 正在排空' },
  PLUGIN_RUNNER_VERSION_MISMATCH: { httpStatus: 409, message: 'Plugin Runner PluginVersion 不匹配' },
  PLUGIN_DISCOVERY_SCHEMA_INVALID: { httpStatus: 422, message: '插件发现结果不符合标准 Schema' },
  AGENT_PLUGIN_MANIFEST_INVALID: { httpStatus: 422, message: 'Agent 插件定义无效' },
  AGENT_PLUGIN_MOUNT_INCOMPATIBLE: { httpStatus: 409, message: 'Agent 插件与目标 Agent 不兼容' },
  AGENT_PLUGIN_BINDING_INVALID: { httpStatus: 422, message: 'Agent 插件资产绑定无效' },
  AGENT_PLAN_SIGNATURE_INVALID: { httpStatus: 403, message: 'Agent 执行计划签名无效' },
  AGENT_AUTHORIZATION_UNAVAILABLE: { httpStatus: 503, message: 'Agent 授权链不可用' },
  AGENT_PLAN_EXPIRED: { httpStatus: 409, message: 'Agent 执行计划已过期' },
  AGENT_V2_ACTION_MODE_MISMATCH: { httpStatus: 422, message: 'Agent v2 Action 与执行模式不匹配' },
  AGENT_PATH_OUTSIDE_ALLOWED_ROOTS: { httpStatus: 403, message: '目标路径超出 Agent 允许范围' },
  AGENT_ACTION_UNREGISTERED: { httpStatus: 422, message: 'Agent Action 未注册' },
  AGENT_ACTION_SCHEMA_UNSUPPORTED: { httpStatus: 422, message: 'Agent Action Schema 不支持' },
  LEGACY_API_REMOVED: { httpStatus: 410, message: '旧 API 已退役' },
  AGENT_ROLLBACK_FAILED: { httpStatus: 500, message: 'Agent 插件回滚失败' },
  AGENT_MANUAL_INTERVENTION_REQUIRED: { httpStatus: 409, message: 'Agent 插件执行需要人工处理' },
  WORKFLOW_ASSERTION_FAILED: { httpStatus: 422, message: '工作流断言失败' },
  WORKFLOW_INTERNAL_READ_ONLY: { httpStatus: 403, message: '插件内部工作流为只读资源' },
  EXECUTION_SOURCE_CONFLICT: { httpStatus: 409, message: '资产执行来源冲突' },
  WORKFLOW_RUNNER_INCOMPATIBLE: { httpStatus: 422, message: '工作流 Runner 与目标不兼容' },
  PLUGIN_WORKFLOW_SOURCE_UNAVAILABLE: { httpStatus: 404, message: '插件工作流来源不可用' },
  PLUGIN_WORKFLOW_HASH_MISMATCH: { httpStatus: 409, message: '插件工作流内容哈希不一致' },
  PLUGIN_WORKFLOW_CAPABILITY_NOT_ALLOWED: { httpStatus: 422, message: '插件能力不能用于创建工作流' },
  PLUGIN_WORKFLOW_BINDING_MISSING: { httpStatus: 404, message: '插件工作流绑定不存在' },
  SECRET_REF_INVALID: { httpStatus: 422, message: 'Secret 引用无效' },
  LDAP_SOURCE_UNREACHABLE: { httpStatus: 502, message: 'LDAP 身份源不可达' },
  LDAP_TLS_FAILED: { httpStatus: 502, message: 'LDAP TLS 连接失败' },
  LDAP_BIND_FAILED: { httpStatus: 401, message: 'LDAP 认证失败' },
  LDAP_SEARCH_FAILED: { httpStatus: 502, message: 'LDAP 查询失败' },
  LDAP_CONFIG_INVALID: { httpStatus: 422, message: 'LDAP 身份源配置无效' },
  LDAP_PROFILE_INVALID: { httpStatus: 422, message: 'LDAP 用户记录无效' },
  NOTIFICATION_CHANNEL_INVALID: { httpStatus: 422, message: '通知渠道配置无效' },
  NOTIFICATION_CHANNEL_UNAVAILABLE: { httpStatus: 503, message: '通知渠道不可用' },
  NOTIFICATION_ROUTE_NOT_FOUND: { httpStatus: 404, message: '通知路由不存在' },
  NOTIFICATION_TEMPLATE_INVALID: { httpStatus: 422, message: '通知模板无效' },
  NOTIFICATION_TEMPLATE_VARIABLE_MISSING: { httpStatus: 422, message: '通知模板变量缺失' },
  NOTIFICATION_DELIVERY_REJECTED: { httpStatus: 409, message: '通知投递被拒绝' },
  NOTIFICATION_DELIVERY_TIMEOUT: { httpStatus: 504, message: '通知投递超时' },
  NOTIFICATION_SECURITY_BLOCKED: { httpStatus: 403, message: '通知安全策略已阻止请求' },
  NOTIFICATION_RETRY_EXHAUSTED: { httpStatus: 409, message: '通知重试次数已耗尽' },
  ...editionLicensingErrorCodes,
};

const genericPluginError: ErrorCodeDefinition = {
  httpStatus: 502,
  message: '插件操作失败',
};

/**
 * 插件错误码属于开放合同，不由宿主维护产品错误码目录。
 * 未注册的插件错误码保留在 AppError.errorCode 中，但 HTTP 映射统一使用通用插件错误。
 */
export const errorCodes: Record<string, ErrorCodeDefinition> = new Proxy(
  registeredErrorCodes,
  {
    get(target, property, receiver) {
      if (typeof property !== 'string') return Reflect.get(target, property, receiver);
      if (Object.prototype.hasOwnProperty.call(target, property)) return Reflect.get(target, property, receiver);
      return genericPluginError;
    },
  },
);

export type ErrorCode = string;
