export const errorCodes = {
  VALIDATION_FAILED: { httpStatus: 400, message: '请求参数不合法' },
  RESOURCE_NOT_FOUND: { httpStatus: 404, message: '资源不存在' },
  RESOURCE_ALREADY_EXISTS: { httpStatus: 409, message: '资源已存在' },
  RESOURCE_VERSION_CONFLICT: { httpStatus: 409, message: '资源版本冲突' },
  IDEMPOTENCY_CONFLICT: { httpStatus: 409, message: '幂等键冲突' },
  TENANT_PARENT_INVALID: { httpStatus: 422, message: '租户父节点无效' },
  TENANT_CYCLE_DETECTED: { httpStatus: 422, message: '租户父子关系不能形成循环' },
  AUTH_UNAUTHENTICATED: { httpStatus: 401, message: '未认证' },
  AUTH_FORBIDDEN: { httpStatus: 403, message: '无权限' },
  SYSTEM_INTERNAL_ERROR: { httpStatus: 500, message: '系统内部错误' },
  CERT_PARSE_FAILED: { httpStatus: 422, message: '证书解析失败' },
  CERT_PRIVATE_KEY_MISSING: { httpStatus: 422, message: '缺少私钥' },
  CERT_PRIVATE_KEY_MISMATCH: { httpStatus: 422, message: '私钥与证书不匹配' },
  CERT_FORMAT_UNSUPPORTED: { httpStatus: 422, message: '证书格式不支持' },
  CERT_DUPLICATE_VERSION: { httpStatus: 409, message: '重复证书版本' },
  CERT_EXPORT_FORMAT_INVALID: { httpStatus: 422, message: '证书导出格式无效' },
  CERT_EXPORT_FAILED: { httpStatus: 422, message: '证书导出失败' },
  CERT_PRIVATE_KEY_REQUIRED: { httpStatus: 422, message: '目标格式需要私钥' },
  CA_TOPOLOGY_INVALID: { httpStatus: 422, message: 'CA 拓扑无效' },
  CA_RISK_CONFIRMATION_REQUIRED: { httpStatus: 409, message: '需要重新确认 CA 风险' },
  CA_TRUST_DOMAIN_STATE_INVALID: { httpStatus: 409, message: 'CA 信任域状态不允许当前操作' },
  CA_PROVIDER_UNAVAILABLE: { httpStatus: 503, message: 'CA Provider 不可用' },
  CA_CAPABILITY_UNSUPPORTED: { httpStatus: 422, message: 'CA 能力不支持' },
  CA_OPERATIONS_VIEW_UNSUPPORTED: { httpStatus: 422, message: 'CA 不支持所选运营视图' },
  CA_OPERATIONS_QUERY_INVALID: { httpStatus: 400, message: 'CA 运营查询参数无效' },
  CA_OPERATIONS_CAPABILITY_UNSUPPORTED: { httpStatus: 422, message: 'CA 不支持所需运营能力' },
  CA_SYNC_ALREADY_RUNNING: { httpStatus: 409, message: '相同范围的 CA 同步正在运行' },
  CA_SYNC_CAPABILITY_UNSUPPORTED: { httpStatus: 422, message: 'CA 不支持历史同步' },
  CA_SYNC_CURSOR_INVALID: { httpStatus: 422, message: 'CA 同步游标无效' },
  CA_SYNC_BATCH_TOO_LARGE: { httpStatus: 422, message: 'CA 同步批次超过限制' },
  CA_SYNC_SOURCE_UNAVAILABLE: { httpStatus: 503, message: 'CA 同步来源不可用' },
  CA_TEMPLATE_MAPPING_CONFLICT: { httpStatus: 409, message: 'CA 模板映射冲突' },
  CA_OPERATION_RESULT_UNKNOWN: { httpStatus: 202, message: 'CA 远程操作结果待确认' },
  CA_KEY_BACKEND_UNAVAILABLE: { httpStatus: 503, message: 'CA 密钥后端不可用' },
  CA_LEDGER_INCONSISTENT: { httpStatus: 409, message: 'CA 签发账本与证书状态不一致' },
  ACME_DIRECTORY_UNAVAILABLE: { httpStatus: 503, message: 'ACME Directory 不可用' },
  ACME_PROVIDER_CONFIG_INVALID: { httpStatus: 422, message: 'ACME Provider 配置无效' },
  ACME_ACCOUNT_INVALID: { httpStatus: 422, message: 'ACME Account 无效' },
  ACME_NONCE_REJECTED: { httpStatus: 503, message: 'ACME Nonce 被拒绝' },
  ACME_RATE_LIMITED: { httpStatus: 429, message: 'ACME CA 请求受到限流' },
  ACME_ORDER_CONFLICT: { httpStatus: 409, message: 'ACME 订单冲突' },
  ACME_ORDER_REQUIRED: { httpStatus: 409, message: 'ACME 申请必须通过订单流程执行' },
  ACME_CHALLENGE_FAILED: { httpStatus: 422, message: 'ACME 域名挑战失败' },
  ACME_CERTIFICATE_MISMATCH: { httpStatus: 422, message: 'ACME 证书与申请材料不匹配' },
  ACME_DOWNLOAD_FAILED: { httpStatus: 503, message: 'ACME 证书下载失败' },
  ACME_SECRET_RESOLVE_DENIED: { httpStatus: 403, message: 'ACME Secret 无法解析' },
  ACME_DEPLOYMENT_BLOCKED: { httpStatus: 422, message: 'ACME 证书部署被阻断' },
  ACME_VERIFY_FAILED: { httpStatus: 422, message: 'ACME 证书 TLS 验证失败' },
  ACME_CLEANUP_FAILED: { httpStatus: 409, message: 'ACME Challenge 清理失败' },
  ACME_LEASE_LOST: { httpStatus: 409, message: 'ACME Worker 租约已丢失' },
  ACME_RENEWAL_FAILED: { httpStatus: 409, message: 'ACME 自动续签失败' },
  ACME_KEY_ROTATION_UNSUPPORTED: { httpStatus: 422, message: '当前密钥托管方式不支持 ACME 密钥轮换' },
  ACME_CERTIFICATE_INVALID: { httpStatus: 422, message: 'ACME 证书材料无效' },
  CERTIFICATE_PROMOTION_BLOCKED: { httpStatus: 409, message: '证书版本 Promotion 被阻断' },
  CA_NODE_SPLIT_BRAIN_RISK: { httpStatus: 409, message: 'CA 节点存在双主风险' },
  CERTIFICATE_PROFILE_VIOLATION: { httpStatus: 422, message: '证书申请不符合 Profile' },
  CERTIFICATE_TRUST_DOMAIN_MISMATCH: { httpStatus: 422, message: '证书申请、Profile 与 CA 不属于同一信任域' },
  CSR_SIGNATURE_INVALID: { httpStatus: 422, message: 'CSR 签名无效' },
  CSR_ASSET_MISMATCH: { httpStatus: 422, message: 'CSR 与应用资产不匹配' },
  CERTIFICATE_ISSUANCE_PENDING: { httpStatus: 202, message: '证书签发处理中' },
  CERTIFICATE_ISSUANCE_CONFLICT: { httpStatus: 409, message: '证书签发冲突' },
  PUBLIC_KEY_MISMATCH: { httpStatus: 422, message: '公钥不匹配' },
  KEY_REUSE_FORBIDDEN: { httpStatus: 409, message: '禁止跨应用复用私钥' },
  CERTIFICATE_REVOCATION_UNSUPPORTED: { httpStatus: 422, message: '当前 CA 不支持证书吊销' },
  TRUST_DISTRIBUTION_FAILED: { httpStatus: 500, message: '信任链分发失败' },
  ASSET_UNREACHABLE: { httpStatus: 422, message: '资产不可达' },
  BINDING_NOT_MANAGED: { httpStatus: 422, message: '绑定未纳管' },
  CAPABILITY_MISSING: { httpStatus: 422, message: '缺少能力' },
  CAPABILITY_EXPIRED: { httpStatus: 422, message: '能力检测已过期' },
  DEPLOYMENT_INVALID_STATE: { httpStatus: 409, message: '部署计划状态不允许该操作' },
  DEPLOYMENT_APPROVAL_REQUIRED: { httpStatus: 422, message: '需要审批' },
  DEPLOYMENT_ASSET_CONTEXT_INVALID: { httpStatus: 422, message: '部署资产上下文无效' },
  DEPLOYMENT_INPUT_CONTRACT_INVALID: { httpStatus: 422, message: '部署输入契约无效' },
  EXECUTION_TIMEOUT: { httpStatus: 504, message: '执行超时' },
  EXECUTION_TARGET_UNAVAILABLE: { httpStatus: 503, message: '执行目标不可用' },
  AGENT_OFFLINE: { httpStatus: 503, message: 'Agent 离线' },
  PLUGIN_SIGNATURE_INVALID: { httpStatus: 422, message: '插件签名无效' },
  PLUGIN_PERMISSION_DENIED: { httpStatus: 403, message: '插件权限不足' },
  PLUGIN_CAPABILITY_EXECUTION_FAILED: { httpStatus: 502, message: '插件能力执行失败' },
  PLUGIN_DISCOVERY_SCHEMA_INVALID: { httpStatus: 422, message: '插件发现结果不符合标准 Schema' },
  AGENT_PLUGIN_MANIFEST_INVALID: { httpStatus: 422, message: 'Agent 插件定义无效' },
  AGENT_PLUGIN_MOUNT_INCOMPATIBLE: { httpStatus: 409, message: 'Agent 插件与目标 Agent 不兼容' },
  AGENT_PLUGIN_BINDING_INVALID: { httpStatus: 422, message: 'Agent 插件资产绑定无效' },
  AGENT_PLAN_SIGNATURE_INVALID: { httpStatus: 403, message: 'Agent 执行计划签名无效' },
  AGENT_PLAN_EXPIRED: { httpStatus: 409, message: 'Agent 执行计划已过期' },
  AGENT_OPERATION_UNSUPPORTED: { httpStatus: 422, message: 'Agent 不支持该原子操作' },
  AGENT_PATH_OUTSIDE_ALLOWED_ROOTS: { httpStatus: 403, message: '目标路径超出 Agent 允许范围' },
  AGENT_COMMAND_NOT_ALLOWED: { httpStatus: 403, message: 'Agent 命令未获授权' },
  AGENT_ATOMIC_OPERATION_FAILED: { httpStatus: 500, message: 'Agent 原子操作执行失败' },
  AGENT_ACTION_UNREGISTERED: { httpStatus: 422, message: 'Agent Action 未注册' },
  AGENT_ACTION_SCHEMA_UNSUPPORTED: { httpStatus: 422, message: 'Agent Action Schema 不支持' },
  HISTORICAL_AGENT_ACTION_MIGRATION_REQUIRED: { httpStatus: 409, message: '历史 Agent Action 需要迁移' },
  HISTORICAL_AGENT_ACTION_AMBIGUOUS: { httpStatus: 409, message: '历史 Agent Action 存在歧义' },
  LEGACY_EXECUTION_RETIRED: { httpStatus: 409, message: 'Legacy 执行类型已下线' },
  LEGACY_API_REMOVED: { httpStatus: 410, message: '旧 API 已退役' },
  AGENT_ROLLBACK_FAILED: { httpStatus: 500, message: 'Agent 插件回滚失败' },
  AGENT_MANUAL_INTERVENTION_REQUIRED: { httpStatus: 409, message: 'Agent 插件执行需要人工处理' },
  WORKFLOW_ASSERTION_FAILED: { httpStatus: 422, message: '工作流断言失败' },
  WORKFLOW_INTERNAL_READ_ONLY: { httpStatus: 403, message: '插件内部工作流为只读资源' },
  EXECUTION_SOURCE_CONFLICT: { httpStatus: 409, message: '资产执行来源冲突' },
  WORKFLOW_RUNNER_INCOMPATIBLE: { httpStatus: 422, message: '工作流 Runner 与目标不兼容' },
  PLUGIN_WORKFLOW_SOURCE_UNAVAILABLE: { httpStatus: 404, message: '插件工作流来源不可用' },
  PLUGIN_WORKFLOW_HASH_MISMATCH: { httpStatus: 409, message: '插件工作流内容哈希不一致' },
  PLUGIN_WORKFLOW_CAPABILITY_NOT_ALLOWED: { httpStatus: 422, message: '插件能力不能用于创建工作流' },
  PLUGIN_WORKFLOW_BINDING_MISSING: { httpStatus: 404, message: '插件工作流绑定不存在' },
  SECRET_REF_INVALID: { httpStatus: 422, message: 'Secret 引用无效' },
  LDAP_SOURCE_UNREACHABLE: { httpStatus: 502, message: 'LDAP 身份源不可达' },
  LDAP_TLS_FAILED: { httpStatus: 502, message: 'LDAP TLS 连接失败' },
  LDAP_BIND_FAILED: { httpStatus: 401, message: 'LDAP 认证失败' },
  LDAP_SEARCH_FAILED: { httpStatus: 502, message: 'LDAP 查询失败' },
  LDAP_CONFIG_INVALID: { httpStatus: 422, message: 'LDAP 身份源配置无效' },
  LDAP_PROFILE_INVALID: { httpStatus: 422, message: 'LDAP 用户记录无效' },
  NOTIFICATION_CHANNEL_INVALID: { httpStatus: 422, message: '通知渠道配置无效' },
  NOTIFICATION_CHANNEL_UNAVAILABLE: { httpStatus: 503, message: '通知渠道不可用' },
  NOTIFICATION_ROUTE_NOT_FOUND: { httpStatus: 404, message: '通知路由不存在' },
  NOTIFICATION_TEMPLATE_INVALID: { httpStatus: 422, message: '通知模板无效' },
  NOTIFICATION_TEMPLATE_VARIABLE_MISSING: { httpStatus: 422, message: '通知模板变量缺失' },
  NOTIFICATION_DELIVERY_REJECTED: { httpStatus: 409, message: '通知投递被拒绝' },
  NOTIFICATION_DELIVERY_TIMEOUT: { httpStatus: 504, message: '通知投递超时' },
  NOTIFICATION_SECURITY_BLOCKED: { httpStatus: 403, message: '通知安全策略已阻止请求' },
  NOTIFICATION_RETRY_EXHAUSTED: { httpStatus: 409, message: '通知重试次数已耗尽' },
  LICENSE_NOT_CONFIGURED: { httpStatus: 409, message: '尚未配置有效许可证' },
  LICENSE_INVALID: { httpStatus: 422, message: '许可证无效' },
  LICENSE_INSTANCE_MISMATCH: { httpStatus: 422, message: '许可证与当前安装实例不匹配' },
  LICENSE_REVOKED: { httpStatus: 403, message: '许可证已撤销' },
  LICENSE_FEATURE_DENIED: { httpStatus: 403, message: '当前套餐未包含该功能' },
  LICENSE_QUOTA_EXCEEDED: { httpStatus: 403, message: '已超过许可证额度' },
  LICENSE_CLOCK_ROLLBACK: { httpStatus: 409, message: '检测到系统时间回退' },
} as const;

export type ErrorCode = keyof typeof errorCodes;
