export const errorCodes = {
  VALIDATION_FAILED: { httpStatus: 400, message: '请求参数不合法' },
  RESOURCE_NOT_FOUND: { httpStatus: 404, message: '资源不存在' },
  RESOURCE_ALREADY_EXISTS: { httpStatus: 409, message: '资源已存在' },
  RESOURCE_VERSION_CONFLICT: { httpStatus: 409, message: '资源版本冲突' },
  IDEMPOTENCY_CONFLICT: { httpStatus: 409, message: '幂等键冲突' },
  AUTH_UNAUTHENTICATED: { httpStatus: 401, message: '未认证' },
  AUTH_FORBIDDEN: { httpStatus: 403, message: '无权限' },
  SYSTEM_INTERNAL_ERROR: { httpStatus: 500, message: '系统内部错误' },
  CERT_PARSE_FAILED: { httpStatus: 422, message: '证书解析失败' },
  CERT_PRIVATE_KEY_MISSING: { httpStatus: 422, message: '缺少私钥' },
  CERT_PRIVATE_KEY_MISMATCH: { httpStatus: 422, message: '私钥与证书不匹配' },
  CERT_FORMAT_UNSUPPORTED: { httpStatus: 422, message: '证书格式不支持' },
  CERT_DUPLICATE_VERSION: { httpStatus: 409, message: '重复证书版本' },
  CERT_EXPORT_FORMAT_INVALID: { httpStatus: 422, message: '证书导出格式无效' },
  CERT_EXPORT_FAILED: { httpStatus: 422, message: '证书导出失败' },
  CERT_PRIVATE_KEY_REQUIRED: { httpStatus: 422, message: '目标格式需要私钥' },
  CA_TOPOLOGY_INVALID: { httpStatus: 422, message: 'CA 拓扑无效' },
  CA_RISK_CONFIRMATION_REQUIRED: { httpStatus: 409, message: '需要重新确认 CA 风险' },
  CA_TRUST_DOMAIN_STATE_INVALID: { httpStatus: 409, message: 'CA 信任域状态不允许当前操作' },
  CA_PROVIDER_UNAVAILABLE: { httpStatus: 503, message: 'CA Provider 不可用' },
  CA_CAPABILITY_UNSUPPORTED: { httpStatus: 422, message: 'CA 能力不支持' },
  CA_OPERATIONS_VIEW_UNSUPPORTED: { httpStatus: 422, message: 'CA 不支持所选运营视图' },
  CA_OPERATIONS_QUERY_INVALID: { httpStatus: 400, message: 'CA 运营查询参数无效' },
  CA_OPERATIONS_CAPABILITY_UNSUPPORTED: { httpStatus: 422, message: 'CA 不支持所需运营能力' },
  CA_SYNC_ALREADY_RUNNING: { httpStatus: 409, message: '相同范围的 CA 同步正在运行' },
  CA_SYNC_CAPABILITY_UNSUPPORTED: { httpStatus: 422, message: 'CA 不支持历史同步' },
  CA_SYNC_CURSOR_INVALID: { httpStatus: 422, message: 'CA 同步游标无效' },
  CA_SYNC_BATCH_TOO_LARGE: { httpStatus: 422, message: 'CA 同步批次超过限制' },
  CA_SYNC_SOURCE_UNAVAILABLE: { httpStatus: 503, message: 'CA 同步来源不可用' },
  CA_TEMPLATE_MAPPING_CONFLICT: { httpStatus: 409, message: 'CA 模板映射冲突' },
  CA_OPERATION_RESULT_UNKNOWN: { httpStatus: 202, message: 'CA 远程操作结果待确认' },
  CA_KEY_BACKEND_UNAVAILABLE: { httpStatus: 503, message: 'CA 密钥后端不可用' },
  CA_LEDGER_INCONSISTENT: { httpStatus: 409, message: 'CA 签发账本与证书状态不一致' },
  CA_NODE_SPLIT_BRAIN_RISK: { httpStatus: 409, message: 'CA 节点存在双主风险' },
  CERTIFICATE_PROFILE_VIOLATION: { httpStatus: 422, message: '证书申请不符合 Profile' },
  CERTIFICATE_TRUST_DOMAIN_MISMATCH: { httpStatus: 422, message: '证书申请、Profile 与 CA 不属于同一信任域' },
  CSR_SIGNATURE_INVALID: { httpStatus: 422, message: 'CSR 签名无效' },
  CSR_ASSET_MISMATCH: { httpStatus: 422, message: 'CSR 与应用资产不匹配' },
  CERTIFICATE_ISSUANCE_PENDING: { httpStatus: 202, message: '证书签发处理中' },
  CERTIFICATE_ISSUANCE_CONFLICT: { httpStatus: 409, message: '证书签发冲突' },
  PUBLIC_KEY_MISMATCH: { httpStatus: 422, message: '公钥不匹配' },
  KEY_REUSE_FORBIDDEN: { httpStatus: 409, message: '禁止跨应用复用私钥' },
  CERTIFICATE_REVOCATION_UNSUPPORTED: { httpStatus: 422, message: '当前 CA 不支持证书吊销' },
  TRUST_DISTRIBUTION_FAILED: { httpStatus: 500, message: '信任链分发失败' },
  ASSET_UNREACHABLE: { httpStatus: 422, message: '资产不可达' },
  BINDING_NOT_MANAGED: { httpStatus: 422, message: '绑定未纳管' },
  CAPABILITY_MISSING: { httpStatus: 422, message: '缺少能力' },
  CAPABILITY_EXPIRED: { httpStatus: 422, message: '能力检测已过期' },
  DEPLOYMENT_INVALID_STATE: { httpStatus: 409, message: '部署计划状态不允许该操作' },
  DEPLOYMENT_APPROVAL_REQUIRED: { httpStatus: 422, message: '需要审批' },
  EXECUTION_TIMEOUT: { httpStatus: 504, message: '执行超时' },
  EXECUTION_TARGET_UNAVAILABLE: { httpStatus: 503, message: '执行目标不可用' },
  AGENT_OFFLINE: { httpStatus: 503, message: 'Agent 离线' },
  PLUGIN_SIGNATURE_INVALID: { httpStatus: 422, message: '插件签名无效' },
  PLUGIN_PERMISSION_DENIED: { httpStatus: 403, message: '插件权限不足' },
  PLUGIN_CAPABILITY_EXECUTION_FAILED: { httpStatus: 502, message: '插件能力执行失败' },
  PLUGIN_DISCOVERY_SCHEMA_INVALID: { httpStatus: 422, message: '插件发现结果不符合标准 Schema' },
  AGENT_PLUGIN_MANIFEST_INVALID: { httpStatus: 422, message: 'Agent 插件定义无效' },
  AGENT_PLUGIN_MOUNT_INCOMPATIBLE: { httpStatus: 409, message: 'Agent 插件与目标 Agent 不兼容' },
  AGENT_PLUGIN_BINDING_INVALID: { httpStatus: 422, message: 'Agent 插件资产绑定无效' },
  AGENT_PLAN_SIGNATURE_INVALID: { httpStatus: 403, message: 'Agent 执行计划签名无效' },
  AGENT_PLAN_EXPIRED: { httpStatus: 409, message: 'Agent 执行计划已过期' },
  AGENT_OPERATION_UNSUPPORTED: { httpStatus: 422, message: 'Agent 不支持该原子操作' },
  AGENT_PATH_OUTSIDE_ALLOWED_ROOTS: { httpStatus: 403, message: '目标路径超出 Agent 允许范围' },
  AGENT_COMMAND_NOT_ALLOWED: { httpStatus: 403, message: 'Agent 命令未获授权' },
  AGENT_ATOMIC_OPERATION_FAILED: { httpStatus: 500, message: 'Agent 原子操作执行失败' },
  AGENT_ROLLBACK_FAILED: { httpStatus: 500, message: 'Agent 插件回滚失败' },
  AGENT_MANUAL_INTERVENTION_REQUIRED: { httpStatus: 409, message: 'Agent 插件执行需要人工处理' },
  WORKFLOW_ASSERTION_FAILED: { httpStatus: 422, message: '工作流断言失败' },
  SECRET_REF_INVALID: { httpStatus: 422, message: 'Secret 引用无效' },
  LDAP_SOURCE_UNREACHABLE: { httpStatus: 502, message: 'LDAP 身份源不可达' },
  LDAP_TLS_FAILED: { httpStatus: 502, message: 'LDAP TLS 连接失败' },
  LDAP_BIND_FAILED: { httpStatus: 401, message: 'LDAP 认证失败' },
  LDAP_SEARCH_FAILED: { httpStatus: 502, message: 'LDAP 查询失败' },
  LDAP_CONFIG_INVALID: { httpStatus: 422, message: 'LDAP 身份源配置无效' },
  LDAP_PROFILE_INVALID: { httpStatus: 422, message: 'LDAP 用户记录无效' },
  NOTIFICATION_CHANNEL_INVALID: { httpStatus: 422, message: '通知渠道配置无效' },
  NOTIFICATION_CHANNEL_UNAVAILABLE: { httpStatus: 503, message: '通知渠道不可用' },
  NOTIFICATION_ROUTE_NOT_FOUND: { httpStatus: 404, message: '通知路由不存在' },
  NOTIFICATION_TEMPLATE_INVALID: { httpStatus: 422, message: '通知模板无效' },
  NOTIFICATION_TEMPLATE_VARIABLE_MISSING: { httpStatus: 422, message: '通知模板变量缺失' },
  NOTIFICATION_DELIVERY_REJECTED: { httpStatus: 409, message: '通知投递被拒绝' },
  NOTIFICATION_DELIVERY_TIMEOUT: { httpStatus: 504, message: '通知投递超时' },
  NOTIFICATION_SECURITY_BLOCKED: { httpStatus: 403, message: '通知安全策略已阻止请求' },
  NOTIFICATION_RETRY_EXHAUSTED: { httpStatus: 409, message: '通知重试次数已耗尽' },
} as const;

export type ErrorCode = keyof typeof errorCodes;
