export const credentialsZhCN = {
  title: '凭据管理', description: '统一管理设备、插件和工作流使用的凭据档案。', empty: '暂无凭据。',
  actions: { refresh: '刷新', configure: '配置', create: '新建凭据', edit: '编辑', save: '保存', close: '关闭', rotate: '轮换', enable: '启用', disable: '停用', delete: '删除', confirmDelete: '确认删除' },
  columns: { name: '名称', kind: '类型', scope: '作用域', username: '用户名', status: '状态', expiresAt: '有效期', remainingTime: '剩余时间', updatedAt: '更新时间', actions: '操作' },
  kinds: { USERNAME_PASSWORD: '用户名与密码', SSH_KEY: 'SSH 私钥', BEARER_TOKEN: 'Bearer Token', API_KEY: 'API Key', CLIENT_CERTIFICATE: '客户端证书', DNS_PROVIDER: 'DNS Provider 凭据', CLOUD_PROVIDER: '云 Provider 凭据', BROWSER_SESSION: '浏览器临时会话' },
  scopes: { global: '全局', team: '团队', zone: '区域', host: '主机', plugin: '插件' },
  fields: { secretRef: 'Secret 引用', credential: '凭据', name: '名称', kind: '类型', scope: '作用域', scopeId: '作用域标识', username: '用户名', deliveryName: 'Header / Query 名称', primarySecret: '密码或机密值', secondarySecret: '私钥', validityDays: '有效期（天）', validityHours: '有效期（小时）', validityMinutes: '有效期（分钟）' },
  placeholders: { selectSecret: '请选择 Secret', select: '请选择凭据', primarySecret: '输入密码或机密值', secondarySecret: '输入私钥', keepSecret: '留空则保留当前密文' },
  hints: { encrypted: '保存后将加密存储，不会返回或展示明文。', encryptedRequired: '此槽位必填，保存后将加密存储且不会返回明文。', keepSecret: '仅在需要更换时输入新值；留空不会覆盖当前密文。', validityDays: '填写 0 或留空表示长期有效。', validityDuration: '浏览器临时会话可分别设置天、小时和分钟；全部填写 0 或留空表示长期有效。' },
  secretLabels: { USERNAME_PASSWORD: '密码', SSH_KEY: 'SSH 私钥', BEARER_TOKEN: 'Bearer Token', API_KEY: 'API Key', CLIENT_CERTIFICATE: '客户端证书', DNS_PROVIDER: 'DNS Provider 配置', BROWSER_SESSION: '浏览器会话参数' },
  cloudProviders: {
    provider: '云服务提供商',
    hint: '选择云服务提供商后，系统会按其签名机制校验并加密保存所需密钥。',
    selectPlaceholder: '请选择已启用的云服务插件',
    unavailable: '该插件的凭据资源不可用，无法创建此类凭据。',
    errors: { load: '加载云服务插件资源失败' },
  },
  status: { errorLabel: '待处理', errorSummary: '未通过迁移或完整性校验', errorHint: '该凭据当前不可使用。编辑并成功保存后会转为停用状态，再由管理员明确启用。' },
  health: { title: '凭据有效性检测', openAria: '查看{name}的有效性检测', test: '手动检测', testing: '检测任务已提交', deviceCount: '关联设备 {count} 台', selectedDevice: '检测设备：{name}（{address}）', checkedAt: '最近检测：{time}', empty: '暂无设备级检测记录。', configTitle: '有效性检测配置', configDescription: '默认关闭。开启后只会使用你选择的一台在线设备，并按该设备插件提供的凭据测试流程检测。', enable: '启用定期有效性检测', deviceLabel: '检测设备', devicePlaceholder: '请选择在线且支持凭据测试的设备', noAssociatedDevice: '当前凭据没有关联设备资产，插件绑定不能作为有效性检测设备。', noOnlineDevice: '当前已关联 {count} 台设备，但没有设备被确认在线。请检查设备网络连通性和在线状态。', onlineNoCredentialTest: '当前有 {onlineCount} 台设备在线，但其当前插件没有提供凭据测试能力，也没有发布凭据测试工作流。请升级或重新导入插件后再开启。', noAvailableOnlineDevice: '当前已关联 {count} 台设备，其中 {onlineCount} 台在线，但没有在线设备同时支持凭据测试。请升级不支持该能力的插件，或选择支持检测的设备。', selectedDeviceUnavailable: '当前选择的设备“{name}”已离线或暂不支持凭据测试，请重新选择在线设备，或关闭有效性检测。', disabledHint: '未启用定期有效性检测。', status: { NORMAL: '正常', DISABLED: '停用', UNUSED: '未使用', UNREACHABLE: '不可达', VALID: '有效', ERROR: '错误' }, errors: { load: '加载有效性检测详情失败', empty: '后端未返回有效性检测配置', test: '提交有效性检测失败' } },
  healthSettings: { title: '有效性检测配置', description: '设置当前租户内所有已启用凭据的定期检测间隔。', intervalLabel: '检测间隔（分钟）', intervalHint: '默认 720 分钟，可设置 1 到 43200 分钟。', errors: { load: '加载检测间隔失败', save: '保存检测间隔失败' } },
  list: { title: '凭据列表', description: '共 {count} 条凭据，机密值始终加密保存。' },
  form: { basicTitle: '基本信息', basicDescription: '定义凭据身份、用途和可见范围。', secretTitle: '机密信息', secretCreateDescription: '直接输入密码或 API Key，系统会统一加密保存。', secretEditDescription: '留空保留原密文；输入新值会在同一事务中完成更新。', browserSessionDescription: '浏览器临时会话不手工填写机密值。保存后，请在记录操作中点击“浏览器获取”，由已发布插件工作流完成登录后的提取和验证。' },
  create: { title: '新建凭据', description: '创建可供设备、插件和工作流复用的加密凭据。' },
  edit: { title: '编辑凭据', description: '更新用户名和机密值前，请先确认下方影响范围。' },
  detail: { title: '凭据详情' }, rotate: { title: '轮换秘密值' },
  usage: { title: '影响范围', description: '以下资源会继续使用更新后的凭据。', total: '当前影响 {count} 项引用', changeWarning: '保存新密码或 API Key 后，这些引用会立即使用新密文。', empty: '当前没有任何引用。', groupEmpty: '无', groups: { devices: '设备（{count}）', workflows: '工作流（{count}）', plugins: '插件绑定（{count}）', acmeCertificates: 'ACME 证书（{count}）', cloudAccounts: '云账号资产（{count}）', browserSessions: '浏览器获取会话（{count}）' } },
  deleteDialog: { title: '删除凭据', description: '删除操作不可恢复，系统会在执行前重新检查引用。', inUseTitle: '无法删除：仍有 {count} 项引用', inUseDescription: '请先解除所有引用，再删除该凭据。', availableTitle: '可以安全删除', availableDescription: '当前没有引用，确认后将同时清理不再使用的加密数据。' },
  errors: { load: '加载凭据失败', save: '保存凭据失败', delete: '删除凭据失败', invalidExpiry: '有效期必须是非负整数；小时不能超过 23，分钟不能超过 59' },
  expiry: { longTerm: '长期有效', expired: '已过期', remainingDays: '剩余 {days} 天', remainingHoursMinutes: '剩余 {hours} 小时 {minutes} 分钟' },
  browser: {
    title: '浏览器临时凭据',
    description: '在后端隔离 Chromium 中完成网页登录，再手动触发插件工作流提取并验证临时凭据。',
    vncTitle: '临时浏览器窗口',
    actions: { open: '浏览器获取', create: '生成浏览器会话', acquire: '获取凭据', acquiring: '获取中…', generatePassword: '随机生成', copyShareUrl: '复制浏览器链接', copied: '已复制', openShareUrl: '直接打开', newSession: '新建会话' },
    fields: { asset: '应用资产', plugin: '获取插件', ttl: '会话有效期（秒）', sharePassword: '临时链接密码（8-128 位）', shareUrl: '浏览器链接', loginUrl: '认证地址 URL', outputs: '输出参数', credentialId: '凭据 ID' },
    hints: { savedLoginUrl: '保存后，点击“浏览器获取”时会自动填充该地址。' },
    session: { title: '登录会话', expiresAt: '到期时间：{time}' },
    saveSuccess: { title: '保存成功', description: '浏览器临时凭据已保存。', message: '已更新现有凭据，应用资产关联保持不变。' },
    errors: { load: '加载获取插件失败', create: '创建浏览器会话失败', acquire: '获取凭据失败', cancel: '取消浏览器会话失败', copy: '复制浏览器链接失败', emptyResponse: '后端未返回有效浏览器会话' },
  },
} as const

export const credentialsZhTW = {
  title: '憑據管理', description: '統一管理裝置、外掛程式和工作流程使用的憑據檔案。', empty: '暫無憑據。',
  actions: { refresh: '重新整理', configure: '設定', create: '新增憑據', edit: '編輯', save: '儲存', close: '關閉', rotate: '輪換', enable: '啟用', disable: '停用', delete: '刪除', confirmDelete: '確認刪除' },
  columns: { name: '名稱', kind: '類型', scope: '作用域', username: '使用者名稱', status: '狀態', expiresAt: '有效期', remainingTime: '剩餘時間', updatedAt: '更新時間', actions: '操作' },
  kinds: { USERNAME_PASSWORD: '使用者名稱與密碼', SSH_KEY: 'SSH 私鑰', BEARER_TOKEN: 'Bearer Token', API_KEY: 'API Key', CLIENT_CERTIFICATE: '用戶端憑證', DNS_PROVIDER: 'DNS Provider 憑據', CLOUD_PROVIDER: '雲端 Provider 憑據', BROWSER_SESSION: '瀏覽器臨時會話' }, scopes: { global: '全域', team: '團隊', zone: '區域', host: '主機', plugin: '外掛程式' },
  fields: { secretRef: 'Secret 引用', credential: '憑據', name: '名稱', kind: '類型', scope: '作用域', scopeId: '作用域識別碼', username: '使用者名稱', deliveryName: 'Header / Query 名稱', primarySecret: '密碼或機密值', secondarySecret: '私鑰', validityDays: '有效期（天）', validityHours: '有效期（小時）', validityMinutes: '有效期（分鐘）' },
  placeholders: { selectSecret: '請選擇 Secret', select: '請選擇憑據', primarySecret: '輸入密碼或機密值', secondarySecret: '輸入私鑰', keepSecret: '留空則保留目前密文' }, hints: { encrypted: '儲存後會加密保存，不會回傳或顯示明文。', encryptedRequired: '此欄位必填，儲存後會加密保存且不會回傳明文。', keepSecret: '僅在需要更換時輸入新值；留空不會覆蓋目前密文。', validityDays: '填寫 0 或留空表示長期有效。', validityDuration: '瀏覽器臨時會話可分別設定天、小時和分鐘；全部填寫 0 或留空表示長期有效。' },
  secretLabels: { USERNAME_PASSWORD: '密碼', SSH_KEY: 'SSH 私鑰', BEARER_TOKEN: 'Bearer Token', API_KEY: 'API Key', CLIENT_CERTIFICATE: '用戶端憑證', DNS_PROVIDER: 'DNS Provider 配置', BROWSER_SESSION: '瀏覽器會話參數' },
  cloudProviders: {
    provider: '雲端服務提供者',
    hint: '選擇雲端服務提供者後，系統會依其簽名機制驗證並加密保存所需金鑰。',
    selectPlaceholder: '請選擇已啟用的雲端服務外掛程式',
    unavailable: '此外掛程式的憑據資源不可用，無法建立此類憑據。',
    errors: { load: '載入雲端服務外掛程式資源失敗' },
  },
  status: { errorLabel: '待處理', errorSummary: '未通過遷移或完整性驗證', errorHint: '此憑據目前不可使用。編輯並成功儲存後會轉為停用，再由管理員明確啟用。' },
  health: { title: '憑據有效性檢測', openAria: '檢視{name}的有效性檢測', test: '手動檢測', testing: '檢測任務已提交', deviceCount: '關聯裝置 {count} 台', selectedDevice: '檢測裝置：{name}（{address}）', checkedAt: '最近檢測：{time}', empty: '暫無裝置級檢測記錄。', configTitle: '有效性檢測設定', configDescription: '預設停用。啟用後只會使用你選擇的一台線上裝置，並依該裝置外掛提供的憑據測試流程檢測。', enable: '啟用定期有效性檢測', deviceLabel: '檢測裝置', devicePlaceholder: '請選擇線上且支援憑據測試的裝置', noAssociatedDevice: '目前憑據沒有關聯裝置資產，外掛綁定不能作為有效性檢測設備。', noOnlineDevice: '目前已關聯 {count} 台裝置，但沒有裝置被確認在線上。請檢查裝置網路連通性和線上狀態。', onlineNoCredentialTest: '目前有 {onlineCount} 台裝置在線上，但其目前外掛沒有提供憑據測試能力，也沒有發布憑據測試工作流程。請升級或重新匯入外掛程式後再啟用。', noAvailableOnlineDevice: '目前已關聯 {count} 台裝置，其中 {onlineCount} 台線上，但沒有線上裝置同時支援憑據測試。請升級不支援該能力的外掛程式，或選擇支援檢測的裝置。', selectedDeviceUnavailable: '目前選擇的裝置「{name}」已離線或暫不支援憑據測試，請重新選擇線上裝置，或停用有效性檢測。', disabledHint: '尚未啟用定期有效性檢測。', status: { NORMAL: '正常', DISABLED: '停用', UNUSED: '未使用', UNREACHABLE: '無法連線', VALID: '有效', ERROR: '錯誤' }, errors: { load: '載入有效性檢測詳情失敗', empty: '後端未返回有效性檢測設定', test: '提交有效性檢測失敗' } },
  healthSettings: { title: '有效性檢測設定', description: '設定目前租戶內所有已啟用憑據的定期檢測間隔。', intervalLabel: '檢測間隔（分鐘）', intervalHint: '預設 720 分鐘，可設定 1 到 43200 分鐘。', errors: { load: '載入檢測間隔失敗', save: '儲存檢測間隔失敗' } },
  list: { title: '憑據清單', description: '共 {count} 筆憑據，機密值始終加密保存。' }, form: { basicTitle: '基本資訊', basicDescription: '定義憑據身分、用途和可見範圍。', secretTitle: '機密資訊', secretCreateDescription: '直接輸入密碼或 API Key，系統會統一加密保存。', secretEditDescription: '留空保留原密文；輸入新值會在同一交易中完成更新。', browserSessionDescription: '瀏覽器臨時會話不手動填寫機密值。儲存後，請在記錄操作中點擊「瀏覽器取得」，由已發布外掛工作流程完成登入後的提取與驗證。' },
  create: { title: '新增憑據', description: '建立供裝置、外掛程式和工作流程重複使用的加密憑據。' }, edit: { title: '編輯憑據', description: '更新使用者名稱和機密值前，請先確認下方影響範圍。' }, detail: { title: '憑據詳情' }, rotate: { title: '輪換祕密值' },
  usage: { title: '影響範圍', description: '以下資源會繼續使用更新後的憑據。', total: '目前影響 {count} 項引用', changeWarning: '儲存新密碼或 API Key 後，這些引用會立即使用新密文。', empty: '目前沒有任何引用。', groupEmpty: '無', groups: { devices: '裝置（{count}）', workflows: '工作流程（{count}）', plugins: '外掛綁定（{count}）', acmeCertificates: 'ACME 憑證（{count}）', cloudAccounts: '雲端帳號資產（{count}）', browserSessions: '瀏覽器取得會話（{count}）' } },
  deleteDialog: { title: '刪除憑據', description: '刪除操作無法復原，系統會在執行前重新檢查引用。', inUseTitle: '無法刪除：仍有 {count} 項引用', inUseDescription: '請先解除所有引用。', availableTitle: '可以安全刪除', availableDescription: '目前沒有引用，確認後會清理不再使用的加密資料。' }, errors: { load: '載入憑據失敗', save: '儲存憑據失敗', delete: '刪除憑據失敗', invalidExpiry: '有效期必須是非負整數；小時不能超過 23，分鐘不能超過 59' },
  expiry: { longTerm: '長期有效', expired: '已過期', remainingDays: '剩餘 {days} 天', remainingHoursMinutes: '剩餘 {hours} 小時 {minutes} 分鐘' },
  browser: {
    title: '瀏覽器臨時憑據',
    description: '在後端隔離 Chromium 中完成網頁登入，再手動觸發外掛工作流程提取並驗證臨時憑據。',
    vncTitle: '臨時瀏覽器視窗',
    actions: { open: '瀏覽器取得', create: '建立瀏覽器會話', acquire: '取得憑據', acquiring: '取得中…', generatePassword: '隨機產生', copyShareUrl: '複製瀏覽器連結', copied: '已複製', openShareUrl: '直接開啟', newSession: '新增會話' },
    fields: { asset: '應用資產', plugin: '取得外掛', ttl: '會話有效期（秒）', sharePassword: '臨時連結密碼（8-128 位）', shareUrl: '瀏覽器連結', loginUrl: '認證地址 URL', outputs: '輸出參數', credentialId: '憑據 ID' },
    hints: { savedLoginUrl: '儲存後，點擊「瀏覽器取得」時會自動填入此地址。' },
    session: { title: '登入會話', expiresAt: '到期時間：{time}' },
    saveSuccess: { title: '儲存成功', description: '瀏覽器臨時憑據已儲存。', message: '已更新現有憑據，應用資產關聯保持不變。' },
    errors: { load: '載入取得外掛失敗', create: '建立瀏覽器會話失敗', acquire: '取得憑據失敗', cancel: '取消瀏覽器會話失敗', copy: '複製瀏覽器連結失敗', emptyResponse: '後端未返回有效瀏覽器會話' },
  },
} as const

export const credentialsEnUS = {
  title: 'Credential Management', description: 'Manage credential profiles shared by devices, plugins, and workflows.', empty: 'No credentials.', actions: { refresh: 'Refresh', configure: 'Configure', create: 'Create credential', edit: 'Edit', save: 'Save', close: 'Close', rotate: 'Rotate', enable: 'Enable', disable: 'Disable', delete: 'Delete', confirmDelete: 'Delete credential' },
  columns: { name: 'Name', kind: 'Type', scope: 'Scope', username: 'Username', status: 'Status', expiresAt: 'Expires', remainingTime: 'Remaining', updatedAt: 'Updated', actions: 'Actions' }, kinds: { USERNAME_PASSWORD: 'Username and password', SSH_KEY: 'SSH private key', BEARER_TOKEN: 'Bearer token', API_KEY: 'API key', CLIENT_CERTIFICATE: 'Client certificate', DNS_PROVIDER: 'DNS provider credential', CLOUD_PROVIDER: 'Cloud provider credential', BROWSER_SESSION: 'Temporary browser session' }, scopes: { global: 'Global', team: 'Team', zone: 'Zone', host: 'Host', plugin: 'Plugin' },
  fields: { secretRef: 'Secret reference', credential: 'Credential', name: 'Name', kind: 'Type', scope: 'Scope', scopeId: 'Scope ID', username: 'Username', deliveryName: 'Header / query name', primarySecret: 'Password or secret value', secondarySecret: 'Private key', validityDays: 'Validity (days)', validityHours: 'Validity (hours)', validityMinutes: 'Validity (minutes)' }, placeholders: { selectSecret: 'Select a secret', select: 'Select a credential', primarySecret: 'Enter a password or secret value', secondarySecret: 'Enter a private key', keepSecret: 'Leave blank to keep the encrypted value' }, hints: { encrypted: 'The value is encrypted at rest and never returned as plaintext.', encryptedRequired: 'This slot is required and will be encrypted without returning plaintext.', keepSecret: 'Enter a value only to replace it; blank keeps the current ciphertext.', validityDays: 'Enter 0 or leave blank for no expiration.', validityDuration: 'Temporary browser sessions support separate days, hours, and minutes; all zero or blank means no expiration.' },
  secretLabels: { USERNAME_PASSWORD: 'Password', SSH_KEY: 'SSH private key', BEARER_TOKEN: 'Bearer token', API_KEY: 'API key', CLIENT_CERTIFICATE: 'Client certificate', DNS_PROVIDER: 'DNS provider configuration', BROWSER_SESSION: 'Browser session parameters' }, list: { title: 'Credential list', description: '{count} credentials; secret values are always encrypted.' }, form: { basicTitle: 'Basic information', basicDescription: 'Define the identity, purpose, and visibility of this credential.', secretTitle: 'Secret information', secretCreateDescription: 'Enter the password or API key directly; it will be encrypted uniformly.', secretEditDescription: 'Leave blank to keep the current ciphertext; enter a replacement when needed.', browserSessionDescription: 'Temporary browser sessions do not accept manually entered secrets. After saving, use “Browser acquire” from the record actions so the published plugin workflow can extract and verify the logged-in session.' },
  cloudProviders: {
    provider: 'Cloud service provider',
    hint: 'The required keys are validated and encrypted according to the selected provider signing mechanism.',
    selectPlaceholder: 'Select an enabled cloud service plugin',
    unavailable: 'This plugin credential resource is unavailable, so this credential cannot be created.',
    errors: { load: 'Failed to load cloud service plugin resources' },
  },
  status: { errorLabel: 'Needs attention', errorSummary: 'Migration or integrity validation failed', errorHint: 'This credential is unavailable. A successful edit moves it to disabled so an administrator can explicitly enable it.' },
  health: { title: 'Credential validity check', openAria: 'View validity check for {name}', test: 'Test now', testing: 'Check task submitted', deviceCount: '{count} linked devices', selectedDevice: 'Check device: {name} ({address})', checkedAt: 'Last check: {time}', empty: 'No device check records.', configTitle: 'Validity check configuration', configDescription: 'Disabled by default. When enabled, only the selected online device is checked through the credential-test workflow provided by its plugin.', enable: 'Enable periodic validity checks', deviceLabel: 'Check device', devicePlaceholder: 'Select an online device with credential-test support', noAssociatedDevice: 'This credential is not linked to a device asset. Plugin bindings cannot be used as a validity-check device.', noOnlineDevice: '{count} linked devices are associated, but none are confirmed online. Check network reachability and connectivity.', onlineNoCredentialTest: '{onlineCount} devices are online, but their current plugin does not provide or publish a credential-test workflow. Upgrade or re-import the plugin before enabling checks.', noAvailableOnlineDevice: '{count} linked devices were found, including {onlineCount} online, but none support credential tests. Upgrade unsupported plugins or select a supported device.', selectedDeviceUnavailable: 'The selected device “{name}” is offline or no longer supports credential tests. Select another online device or disable checks.', disabledHint: 'Periodic validity checks are disabled.', status: { NORMAL: 'Normal', DISABLED: 'Disabled', UNUSED: 'Unused', UNREACHABLE: 'Unreachable', VALID: 'Valid', ERROR: 'Error' }, errors: { load: 'Failed to load validity details', empty: 'The server returned no validity-check configuration', test: 'Failed to submit validity check' } }, healthSettings: { title: 'Validity check configuration', description: 'Set the periodic check interval for enabled credentials in the current tenant.', intervalLabel: 'Check interval (minutes)', intervalHint: 'Default: 720 minutes. Allowed range: 1 to 43200 minutes.', errors: { load: 'Failed to load check interval', save: 'Failed to save check interval' } }, expiry: { longTerm: 'No expiration', expired: 'Expired', remainingDays: '{days} days remaining', remainingHoursMinutes: '{hours}h {minutes}m remaining' },
  create: { title: 'Create credential', description: 'Create an encrypted credential reusable by devices, plugins, and workflows.' }, edit: { title: 'Edit credential', description: 'Review the impact below before updating the username or secret.' }, detail: { title: 'Credential details' }, rotate: { title: 'Rotate secret values' }, usage: { title: 'Impact', description: 'These resources will use the updated credential.', total: '{count} current references', changeWarning: 'They will immediately use the new ciphertext after saving.', empty: 'There are no current references.', groupEmpty: 'None', groups: { devices: 'Devices ({count})', workflows: 'Workflows ({count})', plugins: 'Plugin bindings ({count})', acmeCertificates: 'ACME certificates ({count})', cloudAccounts: 'Cloud account assets ({count})', browserSessions: 'Browser acquisition sessions ({count})' } },
  deleteDialog: { title: 'Delete credential', description: 'Deletion cannot be undone; references are checked again before execution.', inUseTitle: 'Cannot delete: {count} references remain', inUseDescription: 'Remove all references first.', availableTitle: 'Safe to delete', availableDescription: 'No references remain; unused encrypted data will also be removed.' }, errors: { load: 'Failed to load credentials', save: 'Failed to save credential', delete: 'Failed to delete credential', invalidExpiry: 'The validity must use non-negative integers; hours cannot exceed 23 and minutes cannot exceed 59' },
  browser: {
    title: 'Temporary Browser Credential',
    description: 'Sign in through an isolated backend Chromium session, then manually run the plugin workflow to extract and verify the temporary credential.',
    vncTitle: 'Temporary browser window',
    actions: { open: 'Browser acquire', create: 'Generate browser session', acquire: 'Acquire credential', acquiring: 'Acquiring…', generatePassword: 'Generate random', copyShareUrl: 'Copy browser link', copied: 'Copied', openShareUrl: 'Open link', newSession: 'New session' },
    fields: { asset: 'Managed application', plugin: 'Acquisition plugin', ttl: 'Session TTL (seconds)', sharePassword: 'Temporary link password (8-128 characters)', shareUrl: 'Browser link', loginUrl: 'Authentication URL', outputs: 'Output parameters', credentialId: 'Credential ID' },
    hints: { savedLoginUrl: 'After saving, Browser acquire fills this address automatically.' },
    session: { title: 'Login session', expiresAt: 'Expires at {time}' },
    saveSuccess: { title: 'Saved successfully', description: 'The temporary browser credential was saved.', message: 'The existing credential was updated and its managed application association was preserved.' },
    errors: { load: 'Failed to load acquisition plugins', create: 'Failed to create browser session', acquire: 'Failed to acquire credential', cancel: 'Failed to cancel browser session', copy: 'Failed to copy browser link', emptyResponse: 'Backend did not return a valid browser session' },
  },
} as const

export const credentialsJaJP = {
  ...credentialsEnUS,
  title: '資格情報管理', description: 'デバイス、プラグイン、ワークフローで共有する資格情報を管理します。', empty: '資格情報はありません。', actions: { ...credentialsEnUS.actions, refresh: '更新', configure: '設定', create: '資格情報を作成', edit: '編集', save: '保存', close: '閉じる', enable: '有効化', disable: '無効化', delete: '削除', confirmDelete: '削除を確定' }, columns: { ...credentialsEnUS.columns, name: '名前', kind: '種類', scope: 'スコープ', username: 'ユーザー名', status: '状態', updatedAt: '更新日時', actions: '操作' },
  list: { title: '資格情報一覧', description: '{count} 件の資格情報。機密値は常に暗号化されます。' }, create: { title: '資格情報を作成', description: 'デバイス、プラグイン、ワークフローで再利用できる暗号化資格情報を作成します。' }, edit: { title: '資格情報を編集', description: 'ユーザー名または機密値を更新する前に影響範囲を確認してください。' }, usage: { title: '影響範囲', description: '以下のリソースが更新後の資格情報を使用します。', total: '現在 {count} 件の参照があります', changeWarning: '保存後、参照先は新しい暗号値を直ちに使用します。', empty: '現在参照はありません。', groupEmpty: 'なし', groups: { devices: 'デバイス（{count}）', workflows: 'ワークフロー（{count}）', plugins: 'プラグインバインド（{count}）', acmeCertificates: 'ACME 証明書（{count}）', cloudAccounts: 'クラウドアカウント資産（{count}）', browserSessions: 'ブラウザー取得セッション（{count}）' } }, deleteDialog: { title: '資格情報を削除', description: '削除は元に戻せません。実行前に参照を再確認します。', inUseTitle: '削除不可：{count} 件の参照があります', inUseDescription: '先にすべての参照を解除してください。', availableTitle: '安全に削除できます', availableDescription: '参照はありません。未使用の暗号化データも削除されます。' }, errors: { load: '資格情報の読み込みに失敗しました', save: '資格情報の保存に失敗しました', delete: '資格情報の削除に失敗しました', invalidExpiry: '有効期間は 0 以上の整数で指定してください。時間は 23 以下、分は 59 以下です' },
  status: { errorLabel: '要確認', errorSummary: '移行または整合性検証に失敗', errorHint: '現在この資格情報は使用できません。編集して正常に保存すると無効状態になり、その後管理者が明示的に有効化できます。' },
  healthSettings: { title: '有効性チェック設定', description: '現在のテナントで有効な資格情報の定期チェック間隔を設定します。', intervalLabel: 'チェック間隔（分）', intervalHint: '既定値は720分です。1～43200分で設定できます。', errors: { load: 'チェック間隔の読み込みに失敗しました', save: 'チェック間隔の保存に失敗しました' } },
} as const

export const credentialsKoKR = {
  ...credentialsEnUS,
  title: '자격 증명 관리', description: '장치, 플러그인 및 워크플로에서 공유하는 자격 증명을 관리합니다.', empty: '자격 증명이 없습니다.', actions: { ...credentialsEnUS.actions, refresh: '새로 고침', configure: '설정', create: '자격 증명 만들기', edit: '편집', save: '저장', close: '닫기', enable: '활성화', disable: '비활성화', delete: '삭제', confirmDelete: '삭제 확인' }, columns: { ...credentialsEnUS.columns, name: '이름', kind: '유형', scope: '범위', username: '사용자 이름', status: '상태', updatedAt: '업데이트', actions: '작업' },
  list: { title: '자격 증명 목록', description: '총 {count}개이며 비밀 값은 항상 암호화됩니다.' }, create: { title: '자격 증명 만들기', description: '장치, 플러그인 및 워크플로에서 재사용할 암호화 자격 증명을 만듭니다.' }, edit: { title: '자격 증명 편집', description: '사용자 이름이나 비밀 값을 변경하기 전에 영향 범위를 확인하세요.' }, usage: { title: '영향 범위', description: '아래 리소스가 업데이트된 자격 증명을 사용합니다.', total: '현재 참조 {count}개', changeWarning: '저장 후 새 암호문이 즉시 사용됩니다.', empty: '현재 참조가 없습니다.', groupEmpty: '없음', groups: { devices: '장치 ({count})', workflows: '워크플로 ({count})', plugins: '플러그인 바인딩 ({count})', acmeCertificates: 'ACME 인증서 ({count})', cloudAccounts: '클라우드 계정 자산 ({count})', browserSessions: '브라우저 수집 세션 ({count})' } }, deleteDialog: { title: '자격 증명 삭제', description: '삭제는 되돌릴 수 없으며 실행 전에 참조를 다시 검사합니다.', inUseTitle: '삭제 불가: 참조 {count}개', inUseDescription: '먼저 모든 참조를 해제하세요.', availableTitle: '안전하게 삭제 가능', availableDescription: '참조가 없으며 사용하지 않는 암호화 데이터도 삭제됩니다.' }, errors: { load: '자격 증명을 불러오지 못했습니다', save: '자격 증명을 저장하지 못했습니다', delete: '자격 증명을 삭제하지 못했습니다', invalidExpiry: '유효 기간은 음이 아닌 정수여야 하며 시간은 23, 분은 59를 초과할 수 없습니다' },
  status: { errorLabel: '확인 필요', errorSummary: '마이그레이션 또는 무결성 검증 실패', errorHint: '현재 사용할 수 없습니다. 편집 후 정상적으로 저장하면 비활성 상태로 전환되며 관리자가 명시적으로 활성화할 수 있습니다.' },
  healthSettings: { title: '유효성 검사 설정', description: '현재 테넌트에서 활성화된 자격 증명의 정기 검사 간격을 설정합니다.', intervalLabel: '검사 간격(분)', intervalHint: '기본값은 720분이며 1~43200분으로 설정할 수 있습니다.', errors: { load: '검사 간격을 불러오지 못했습니다', save: '검사 간격을 저장하지 못했습니다' } },
} as const

export const credentialsFrFR = {
  ...credentialsEnUS,
  title: 'Gestion des identifiants', description: 'Gérer les profils partagés par les appareils, les plugins et les workflows.', empty: 'Aucun identifiant.', actions: { ...credentialsEnUS.actions, refresh: 'Actualiser', configure: 'Configurer', create: 'Créer un identifiant', edit: 'Modifier', save: 'Enregistrer', close: 'Fermer', enable: 'Activer', disable: 'Désactiver', delete: 'Supprimer', confirmDelete: 'Confirmer la suppression' }, columns: { ...credentialsEnUS.columns, name: 'Nom', kind: 'Type', scope: 'Portée', username: 'Utilisateur', status: 'État', updatedAt: 'Mise à jour', actions: 'Actions' },
  list: { title: 'Liste des identifiants', description: '{count} identifiants ; les valeurs secrètes restent chiffrées.' }, create: { title: 'Créer un identifiant', description: 'Créer un identifiant chiffré réutilisable par les appareils, plugins et workflows.' }, edit: { title: 'Modifier l’identifiant', description: 'Vérifiez l’impact avant de modifier l’utilisateur ou le secret.' }, usage: { title: 'Impact', description: 'Ces ressources utiliseront l’identifiant mis à jour.', total: '{count} références actuelles', changeWarning: 'Elles utiliseront immédiatement la nouvelle valeur chiffrée.', empty: 'Aucune référence actuelle.', groupEmpty: 'Aucun', groups: { devices: 'Appareils ({count})', workflows: 'Workflows ({count})', plugins: 'Liaisons de plugin ({count})', acmeCertificates: 'Certificats ACME ({count})', cloudAccounts: 'Actifs de compte cloud ({count})', browserSessions: 'Sessions d’acquisition navigateur ({count})' } }, deleteDialog: { title: 'Supprimer l’identifiant', description: 'La suppression est irréversible ; les références sont revérifiées.', inUseTitle: 'Suppression impossible : {count} références', inUseDescription: 'Supprimez d’abord toutes les références.', availableTitle: 'Suppression possible', availableDescription: 'Aucune référence ; les données chiffrées inutilisées seront supprimées.' }, errors: { load: 'Échec du chargement des identifiants', save: 'Échec de l’enregistrement', delete: 'Échec de la suppression', invalidExpiry: 'La durée doit utiliser des entiers positifs ou nuls ; les heures ne peuvent pas dépasser 23 et les minutes 59' },
  status: { errorLabel: 'À traiter', errorSummary: 'Échec de migration ou de validation', errorHint: 'Cet identifiant est indisponible. Une modification enregistrée le passe en état désactivé avant activation explicite.' },
  healthSettings: { title: 'Configuration du contrôle de validité', description: 'Définissez l’intervalle de contrôle périodique des identifiants actifs du locataire courant.', intervalLabel: 'Intervalle de contrôle (minutes)', intervalHint: 'Valeur par défaut : 720 minutes. Plage autorisée : 1 à 43200 minutes.', errors: { load: 'Échec du chargement de l’intervalle', save: 'Échec de l’enregistrement de l’intervalle' } },
} as const

export const credentialsPtBR = {
  ...credentialsEnUS,
  title: 'Gerenciamento de credenciais', description: 'Gerencie perfis compartilhados por dispositivos, plugins e fluxos de trabalho.', empty: 'Nenhuma credencial.', actions: { ...credentialsEnUS.actions, refresh: 'Atualizar', configure: 'Configurar', create: 'Criar credencial', edit: 'Editar', save: 'Salvar', close: 'Fechar', enable: 'Ativar', disable: 'Desativar', delete: 'Excluir', confirmDelete: 'Confirmar exclusão' }, columns: { ...credentialsEnUS.columns, name: 'Nome', kind: 'Tipo', scope: 'Escopo', username: 'Usuário', status: 'Status', updatedAt: 'Atualizado em', actions: 'Ações' },
  list: { title: 'Lista de credenciais', description: '{count} credenciais; os valores secretos permanecem criptografados.' }, create: { title: 'Criar credencial', description: 'Crie uma credencial criptografada reutilizável por dispositivos, plugins e fluxos.' }, edit: { title: 'Editar credencial', description: 'Revise o impacto antes de alterar o usuário ou o segredo.' }, usage: { title: 'Impacto', description: 'Estes recursos usarão a credencial atualizada.', total: '{count} referências atuais', changeWarning: 'Elas usarão imediatamente o novo valor criptografado.', empty: 'Não há referências atuais.', groupEmpty: 'Nenhum', groups: { devices: 'Dispositivos ({count})', workflows: 'Fluxos ({count})', plugins: 'Vínculos de plugin ({count})', acmeCertificates: 'Certificados ACME ({count})', cloudAccounts: 'Ativos de conta em nuvem ({count})', browserSessions: 'Sessões de aquisição no navegador ({count})' } }, deleteDialog: { title: 'Excluir credencial', description: 'A exclusão é irreversível; as referências serão verificadas novamente.', inUseTitle: 'Não é possível excluir: {count} referências', inUseDescription: 'Remova primeiro todas as referências.', availableTitle: 'É seguro excluir', availableDescription: 'Não há referências; os dados criptografados não utilizados também serão removidos.' }, errors: { load: 'Falha ao carregar credenciais', save: 'Falha ao salvar credencial', delete: 'Falha ao excluir credencial', invalidExpiry: 'A validade deve usar inteiros não negativos; as horas não podem exceder 23 e os minutos não podem exceder 59' },
  status: { errorLabel: 'Requer atenção', errorSummary: 'Falha na migração ou validação', errorHint: 'Esta credencial está indisponível. Uma edição salva a move para desativada antes da ativação explícita.' },
  healthSettings: { title: 'Configuração da verificação de validade', description: 'Defina o intervalo da verificação periódica das credenciais ativas do locatário atual.', intervalLabel: 'Intervalo de verificação (minutos)', intervalHint: 'Padrão: 720 minutos. Faixa permitida: 1 a 43200 minutos.', errors: { load: 'Falha ao carregar o intervalo', save: 'Falha ao salvar o intervalo' } },
} as const

export const credentialsRuRU = {
  ...credentialsEnUS,
  title: 'Управление учетными данными', description: 'Управление профилями для устройств, плагинов и рабочих процессов.', empty: 'Учетных данных нет.', actions: { ...credentialsEnUS.actions, refresh: 'Обновить', configure: 'Настроить', create: 'Создать учетные данные', edit: 'Изменить', save: 'Сохранить', close: 'Закрыть', enable: 'Включить', disable: 'Отключить', delete: 'Удалить', confirmDelete: 'Подтвердить удаление' }, columns: { ...credentialsEnUS.columns, name: 'Имя', kind: 'Тип', scope: 'Область', username: 'Пользователь', status: 'Статус', updatedAt: 'Обновлено', actions: 'Действия' },
  list: { title: 'Список учетных данных', description: 'Всего {count}; секретные значения всегда зашифрованы.' }, create: { title: 'Создать учетные данные', description: 'Создайте зашифрованные данные для устройств, плагинов и процессов.' }, edit: { title: 'Изменить учетные данные', description: 'Проверьте влияние перед изменением пользователя или секрета.' }, usage: { title: 'Влияние', description: 'Эти ресурсы будут использовать обновленные данные.', total: 'Текущих ссылок: {count}', changeWarning: 'После сохранения будет сразу использовано новое зашифрованное значение.', empty: 'Текущих ссылок нет.', groupEmpty: 'Нет', groups: { devices: 'Устройства ({count})', workflows: 'Процессы ({count})', plugins: 'Привязки плагинов ({count})', acmeCertificates: 'Сертификаты ACME ({count})', cloudAccounts: 'Активы облачных аккаунтов ({count})', browserSessions: 'Сессии получения в браузере ({count})' } }, deleteDialog: { title: 'Удалить учетные данные', description: 'Удаление необратимо; ссылки будут проверены повторно.', inUseTitle: 'Удаление невозможно: ссылок {count}', inUseDescription: 'Сначала удалите все ссылки.', availableTitle: 'Можно безопасно удалить', availableDescription: 'Ссылок нет; неиспользуемые зашифрованные данные также будут удалены.' }, errors: { load: 'Не удалось загрузить учетные данные', save: 'Не удалось сохранить учетные данные', delete: 'Не удалось удалить учетные данные', invalidExpiry: 'Срок действия должен задаваться неотрицательными целыми числами; часы не более 23, минуты не более 59' },
  status: { errorLabel: 'Требует внимания', errorSummary: 'Ошибка миграции или проверки целостности', errorHint: 'Учетные данные недоступны. После успешного редактирования они перейдут в отключенное состояние для явного включения администратором.' },
  healthSettings: { title: 'Настройка проверки действительности', description: 'Задайте интервал периодической проверки активных учетных данных текущего арендатора.', intervalLabel: 'Интервал проверки (минуты)', intervalHint: 'По умолчанию: 720 минут. Допустимый диапазон: от 1 до 43200 минут.', errors: { load: 'Не удалось загрузить интервал проверки', save: 'Не удалось сохранить интервал проверки' } },
} as const
