export const internalCaEnglish = {
  title: 'Internal CA', description: 'Manage internal certificate authorities, application certificate lifecycle, CA nodes, and certificate reuse risks.',
  tabs: { trustDomains: 'CA trust domains', authorities: 'Authorities', profiles: 'Profiles', requests: 'Requests', operations: 'Operations', risks: 'Reuse risks' },
  topology: { rootOnly: 'Root CA only', rootOnlyDescription: 'The root CA performs daily issuance and remains online.', rootOnlyRisk: 'High risk: root key compromise affects the entire trust domain.', intermediate: 'Root CA + intermediate CA', intermediateDescription: 'Keep the root offline and use an intermediate CA for daily issuance.', recommended: 'Recommended: isolate the root key and reduce the issuance blast radius.' },
  sections: { trustDomain: 'Create CA trust domain', provider: 'CA Provider', authorityWizard: 'CA creation wizard', riskSummary: 'Security decision summary', profile: 'Create certificate profile', request: 'Create application certificate request', revocation: 'Create revocation task', trust: 'Create trust distribution', remediation: 'Remediation preview' },
  fields: { name: 'Name', code: 'Code', purpose: 'Purpose', isolationLevel: 'Isolation level', defaultTrustDomain: 'Set as default trust domain', trustDomain: 'CA trust domain', providerType: 'Provider type', deploymentMode: 'Deployment mode', platform: 'Runtime platform', provider: 'CA Provider', commonName: 'Common Name', securityDomain: 'Security domain', topology: 'CA topology', dnsSuffixes: 'Allowed DNS suffixes', validityDays: 'Maximum validity days', renewalDays: 'Renewal window days', requireApproval: 'Require approval before issuance', applicationAssetId: 'Application asset ID', authority: 'Certificate authority', profileVersionId: 'Profile version ID', sans: 'SAN list', custodyMode: 'Key custody mode', certificateVersionId: 'Certificate version ID', reason: 'Revocation reason', targetIds: 'Target ID list' },
  actions: { refresh: 'Refresh', createTrustDomain: 'Create trust domain', createProvider: 'Create provider', previewRisk: 'Preview risk', createAuthority: 'Create CA', createProfile: 'Create profile', createRequest: 'Submit request', approve: 'Approve', retry: 'Retry', queryResult: 'Query result', scanRenewals: 'Scan renewals', createRevocation: 'Create revocation', createTrust: 'Create trust distribution', previewRemediation: 'Preview remediation' },
  placeholders: { dnsSuffixes: 'example.com, office.example.com', sans: 'oa.example.com, 10.0.0.10' },
  messages: { loadFailed: 'Failed to load internal CA data.', actionFailed: 'The operation failed. Check input, permissions, and approval status.', trustDomainCreated: 'CA trust domain created.', providerCreated: 'CA provider created.', authorityCreated: 'Certificate authority created.', profileCreated: 'Certificate profile created.', requestCreated: 'Certificate request submitted.', requestApproved: 'Certificate request approved.', requestRetried: 'Certificate issuance retried.', requestQueried: 'Remote issuance result refreshed.', renewalScanned: 'Renewal scan completed.', revocationCreated: 'Revocation task created and awaiting approval.', revocationApproved: 'Certificate revocation approved.', trustCreated: 'Trust distribution created and awaiting approval.', trustApproved: 'Trust distribution approved.' },
  metrics: { nodes: 'CA nodes', renewals: 'Renewals', revocations: 'Revocations', trust: 'Trust distributions', totalRisks: 'Total risks', critical: 'Critical risks', affectedAssets: 'Affected application assets' },
  labels: { defaultTrustDomain: 'Default trust domain', independentTrustDomain: 'Independent root trust boundary', trustDomainCount: '{count} CA trust domains', versionCount: '{count} versions', assetCount: '{count} application assets', requestCount: '{count} independent certificate requests will be created' },
  riskTypes: { certificate_fingerprint_reuse: 'Same certificate reused across assets', public_key_reuse: 'Same public key reused across assets' },
  common: { unknown: 'Unknown' }, aria: { tabs: 'Internal CA navigation' },
} as const
