import type { CapabilityDefinition } from '../../../shared/contracts/capability-contracts.js';

export const builtInCapabilityDefinitions = [
  definition('agent.full.online', '完整 Agent 在线', 'agent', 'low', 'boolean', false, '目标 Full Agent 可连接控制台'),
  definition('agent.legacy.online', '轻量 Agent 在线', 'agent', 'low', 'boolean', false, '目标 Legacy Agent 可连接控制台'),
  definition('agent.gateway.online', 'Gateway Agent 在线', 'agent', 'low', 'boolean', false, '网关 Agent 可用'),
  definition('agent.task.receive', 'Agent 接收任务', 'agent', 'medium', 'boolean', false, 'Agent 能接收执行任务'),
  definition('agent.log.report', 'Agent 回传日志', 'agent', 'low', 'boolean', false, 'Agent 能回传执行日志'),
  definition('agent.capability.probe', 'Agent 能力探测', 'agent', 'low', 'boolean', false, 'Agent 能主动探测本机能力'),
  definition('runtime.windows.compatibility_agent', 'Windows 兼容版 Agent Runtime', 'agent', 'medium', 'boolean', false, '目标由独立 Windows Compatibility Agent 正式运行时管理'),
  definition('gateway.reachable', '网关可达目标', 'gateway', 'medium', 'boolean', true, 'Gateway 能从所在 Zone 探测目标网络'),
  definition('gateway.probe.tcp', 'Gateway TCP 探测', 'gateway', 'low', 'boolean', true, 'Gateway 能探测目标 TCP 端口可达性'),
  definition('gateway.probe.http', 'Gateway HTTP 探测', 'gateway', 'low', 'boolean', true, 'Gateway 能探测目标 HTTP/HTTPS 可达性'),
  definition('gateway.probe.agent', 'Gateway Agent 探测', 'gateway', 'low', 'boolean', true, 'Gateway 能探测区域内 Agent 可用性'),
  definition('gateway.forward.agent_task', 'Gateway 转发 Agent 任务', 'gateway', 'medium', 'boolean', true, 'Gateway 能把任务转发给区域内 Agent'),
  definition('gateway.forward.direct_control', 'Gateway 转发 Direct Control', 'gateway', 'medium', 'boolean', true, 'Gateway 能把 Direct Control 请求转发给区域内 Agent'),
  definition('file.read', '文件读取', 'file', 'medium', 'boolean', true, '能读取目标路径文件'),
  definition('file.write', '文件写入', 'file', 'high', 'boolean', true, '能写入目标路径文件'),
  definition('file.backup', '文件备份', 'file', 'high', 'boolean', true, '能备份证书、配置或 keystore'),
  definition('file.restore', '文件恢复', 'file', 'critical', 'boolean', true, '能从备份恢复文件'),
  definition('file.atomic_replace', '原子替换', 'file', 'high', 'boolean', true, '能以安全方式替换文件'),
  definition('file.permission.set', '文件权限设置', 'file', 'high', 'boolean', true, '能设置 owner、mode、ACL 等权限'),
  definition('process.exec', '执行命令', 'process', 'critical', 'string_array', true, '能执行系统命令'),
  definition('process.exec.capture_output', '捕获命令输出', 'process', 'medium', 'boolean', true, '能读取 stdout/stderr 和退出码'),
  definition('process.script.run', '执行脚本', 'process', 'critical', 'boolean', true, '能执行脚本文件或脚本文本'),
  definition('service.status', '查询服务状态', 'service', 'medium', 'boolean', true, '能查询服务运行状态'),
  definition('service.reload', '重载服务', 'service', 'high', 'boolean', true, '能 reload 服务'),
  definition('service.restart', '重启服务', 'service', 'critical', 'boolean', true, '能 restart 服务'),
  definition('service.stop_start', '停止启动服务', 'service', 'critical', 'boolean', true, '能 stop/start 服务'),
  definition('tls.remote_probe', '远程 TLS 探测', 'tls', 'low', 'boolean', true, '能从网络端口读取证书链'),
  definition('tls.local_verify', '本地证书校验', 'tls', 'low', 'boolean', true, '能校验证书文件、key、chain 是否匹配'),
  definition('tls.chain_validate', '证书链校验', 'tls', 'low', 'boolean', true, '能验证证书链完整性'),
  definition('tls.fingerprint.compare', '指纹比较', 'tls', 'low', 'boolean', true, '能比较部署前后证书指纹'),
  definition('windows.certstore.list', '列出证书存储', 'windows', 'medium', 'boolean', true, '能读取 Windows Cert Store'),
  definition('windows.certstore.import_pfx', '导入 PFX', 'windows', 'critical', 'boolean', true, '能向 Windows 证书库导入 PFX'),
  definition('windows.certstore.remove', '删除证书', 'windows', 'critical', 'boolean', true, '能从证书库删除证书'),
  definition('windows.certstore.private_key_acl', '设置私钥 ACL', 'windows', 'critical', 'boolean', true, '能设置私钥访问权限'),
  definition('windows.certutil.import_pfx', 'certutil 导入 PFX', 'windows', 'critical', 'boolean', true, '老 Windows 兼容路径'),
  definition('windows.powershell.exec', 'PowerShell 执行', 'windows', 'critical', 'boolean', true, '能执行 PowerShell'),
  definition('windows.cmd.exec', 'CMD 执行', 'windows', 'critical', 'boolean', true, '能执行 cmd 命令'),
  definition('iis.discover', 'IIS 发现', 'iis', 'medium', 'boolean', true, '能发现 IIS Site 和 Binding'),
  definition('iis.binding.list', 'IIS Binding 列出', 'iis', 'medium', 'boolean', true, '能读取 HTTPS Binding'),
  definition('iis.binding.update', 'IIS Binding 更新', 'iis', 'critical', 'boolean', true, '能更新 HTTPS Binding 的证书'),
  definition('iis.app_pool.recycle', 'IIS 应用池回收', 'iis', 'high', 'boolean', true, '能回收应用池'),
  definition('iis.service.restart', 'IIS 服务重启', 'iis', 'critical', 'boolean', true, '能重启 IIS 相关服务'),
  definition('linux.systemd.available', 'systemd 可用', 'linux', 'medium', 'boolean', true, '能使用 systemctl'),
  definition('linux.initd.available', 'init.d 可用', 'linux', 'medium', 'boolean', true, '能使用 /etc/init.d'),
  definition('linux.service.command', 'service 命令可用', 'linux', 'medium', 'boolean', true, '能使用 service 命令'),
  definition('linux.openssl.available', 'openssl 可用', 'linux', 'low', 'boolean', true, '能使用 openssl 做证书校验'),
  definition('linux.sudo.available', 'sudo 可用', 'linux', 'high', 'boolean', true, '能通过 sudo 执行命令'),
  definition('nginx.discover', 'NGINX 发现', 'nginx', 'medium', 'boolean', true, '能发现 NGINX 实例和配置路径'),
  definition('nginx.config_dump', 'NGINX 配置展开', 'nginx', 'medium', 'boolean', true, '能执行或等效获取 nginx -T'),
  definition('nginx.config_parse', 'NGINX 配置解析', 'nginx', 'low', 'boolean', true, '能解析 ssl_certificate 等配置'),
  definition('nginx.config_test', 'NGINX 配置测试', 'nginx', 'high', 'boolean', true, '能执行 nginx -t 或等效测试'),
  definition('nginx.cert.install', 'NGINX 证书安装', 'nginx', 'high', 'boolean', true, '能更新 NGINX 证书文件'),
  definition('nginx.reload', 'NGINX 重载', 'nginx', 'high', 'boolean', true, '能执行平滑 reload'),
  definition('apache.discover', 'Apache 发现', 'apache', 'medium', 'boolean', true, '能发现 Apache/httpd 实例'),
  definition('apache.vhost_list', '虚拟主机列出', 'apache', 'medium', 'boolean', true, '能执行 apachectl -S 或等效方式'),
  definition('apache.config_parse', 'Apache 配置解析', 'apache', 'low', 'boolean', true, '能解析证书指令'),
  definition('apache.config_test', 'Apache 配置测试', 'apache', 'high', 'boolean', true, '能执行 configtest'),
  definition('apache.cert.install', 'Apache 证书安装', 'apache', 'high', 'boolean', true, '能更新 Apache 证书文件'),
  definition('apache.reload', 'Apache 重载', 'apache', 'high', 'boolean', true, '能 reload Apache/httpd'),
  definition('tomcat.discover', 'Tomcat 发现', 'tomcat', 'medium', 'boolean', true, '能发现 Tomcat 实例'),
  definition('tomcat.server_xml.parse', 'server.xml 解析', 'tomcat', 'medium', 'boolean', true, '能解析 TLS Connector'),
  definition('tomcat.keystore.read', 'keystore 读取', 'tomcat', 'high', 'boolean', true, '能读取 JKS/PFX/PKCS12 摘要'),
  definition('tomcat.keystore.replace', 'keystore 替换', 'tomcat', 'critical', 'boolean', true, '能替换 keystore'),
  definition('tomcat.restart', 'Tomcat 重启', 'tomcat', 'critical', 'boolean', true, '能重启 Tomcat'),
  definition('tomcat.connector.verify', 'Connector 验证', 'tomcat', 'medium', 'boolean', true, '能验证 Tomcat TLS 端口'),
  definition('ssh.connect', 'SSH 连接', 'remote', 'medium', 'boolean', true, '能建立 SSH 连接'),
  definition('ssh.exec', 'SSH 命令执行', 'remote', 'critical', 'boolean', true, '能通过 SSH 执行命令'),
  definition('ssh.sftp', 'SFTP 文件传输', 'remote', 'high', 'boolean', true, '能通过 SFTP 上传下载'),
  definition('ssh.scp', 'SCP 文件传输', 'remote', 'high', 'boolean', true, '能通过 SCP 上传下载'),
  definition('ssh.sudo', 'SSH sudo', 'remote', 'critical', 'boolean', true, '能通过 sudo 提权执行'),
  definition('winrm.connect', 'WinRM 连接', 'remote', 'medium', 'boolean', true, '能连接 WinRM'),
  definition('winrm.exec', 'WinRM 命令执行', 'remote', 'critical', 'boolean', true, '能通过 WinRM 执行命令'),
  definition('smb.copy', 'SMB 文件复制', 'remote', 'high', 'boolean', true, '能通过 SMB 复制文件'),
  definition('wmi.exec', 'WMI 命令执行', 'remote', 'critical', 'boolean', true, '能通过 WMI 执行命令'),
  definition('http.request', 'HTTP 请求', 'http', 'medium', 'boolean', true, '能发送 HTTP 请求'),
  definition('http.auth.basic', 'Basic 认证', 'http', 'medium', 'boolean', true, '支持 Basic Auth'),
  definition('http.auth.bearer', 'Bearer 认证', 'http', 'medium', 'boolean', true, '支持 Bearer Token'),
  definition('http.cookie.session', 'Cookie 会话', 'http', 'medium', 'boolean', true, '支持 Cookie 会话保持'),
  definition('http.file_upload', '文件上传', 'http', 'high', 'boolean', true, '支持上传证书或 key'),
  definition('http.response.assert', '响应断言', 'http', 'low', 'boolean', true, '支持对响应做断言'),
  definition('curl.workflow.run', 'CURL 工作流执行', 'http', 'high', 'boolean', true, '能执行结构化 CURL 工作流'),
  definition('manual.operation', '人工操作', 'manual', 'medium', 'boolean', true, '目标只能由人工操作'),
  definition('manual.confirm', '人工确认', 'manual', 'medium', 'boolean', true, '需要人工确认结果'),
  definition('manual.result_upload', '人工结果上传', 'manual', 'low', 'boolean', true, '用户上传执行结果或截图'),
  definition('manual.record', '人工记录', 'manual', 'low', 'boolean', true, '用户补充只读记录用于监控'),
  definition('script_package.generate', '脚本包生成', 'manual', 'medium', 'boolean', true, '平台能生成脚本包'),
  definition('script_package.rollback_generate', '回滚脚本包生成', 'manual', 'high', 'boolean', true, '平台能生成回滚脚本'),
  definition('rollback.snapshot', '创建回滚快照', 'rollback', 'high', 'boolean', true, '能创建部署前快照'),
  definition('rollback.restore', '执行回滚恢复', 'rollback', 'critical', 'boolean', true, '能恢复旧证书或配置'),
  definition('rollback.verify', '回滚验证', 'rollback', 'medium', 'boolean', true, '能验证回滚后状态'),
  definition('service.reload.custom', '自定义服务重载', 'service', 'high', 'string_array', true, '兼容旧声明，后续迁移到 process.exec', {
    deprecated: true,
    replacedBy: 'process.exec',
    aliases: ['custom.reload.command'],
  }),
] as const satisfies readonly CapabilityDefinition[];

export const builtInCapabilityKeys = builtInCapabilityDefinitions.map((item) => item.key);

export const capabilityDefinitionMap = new Map<string, CapabilityDefinition>();
for (const definitionItem of builtInCapabilityDefinitions) {
  capabilityDefinitionMap.set(definitionItem.key, definitionItem);
  for (const alias of definitionItem.aliases) {
    capabilityDefinitionMap.set(alias, definitionItem);
  }
}

export const capabilitiesSchemaBoundary = {
  module: 'capabilities',
  dictionaryVersion: `builtin-${builtInCapabilityDefinitions.length}`,
  builtInCapabilityKeys,
} as const;

function definition(
  key: string,
  name: string,
  category: string,
  riskLevel: CapabilityDefinition['riskLevel'],
  valueType: CapabilityDefinition['valueType'],
  manualAllowed: boolean,
  description: string,
  overrides: Partial<Omit<CapabilityDefinition, 'key' | 'name' | 'category' | 'riskLevel' | 'valueType' | 'manualAllowed' | 'description'>> = {},
): CapabilityDefinition {
  return {
    key,
    name,
    category,
    riskLevel,
    valueType,
    manualAllowed,
    description,
    deprecated: overrides.deprecated ?? false,
    replacedBy: overrides.replacedBy,
    aliases: overrides.aliases ?? [],
    allowedValues: overrides.allowedValues,
  };
}
