# syntax=docker/dockerfile:1.7

ARG NODE_IMAGE=node:22-bookworm-slim
ARG WEB_IMAGE=nginx:1.27-alpine
ARG VITE_PRODUCT_EDITION=public

FROM ${NODE_IMAGE} AS build
ARG VITE_PRODUCT_EDITION
ENV VITE_PRODUCT_EDITION=${VITE_PRODUCT_EDITION}
WORKDIR /src/web
COPY web/package.json web/package-lock.json ./
COPY version /src/version
RUN npm ci
COPY web ./
COPY docs/Documentation/.vitepress/dist ./public/docs
RUN npm run build

FROM ${WEB_IMAGE}
COPY --from=build /src/web/dist /usr/share/nginx/html
COPY docker/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
