# syntax=docker/dockerfile:1.7

ARG NODE_IMAGE=node:22-bookworm-slim
ARG WEB_IMAGE=nginx:1.27-alpine
ARG VITE_PRODUCT_EDITION=public
ARG DOCS_VERSION=1.0.0

FROM ${NODE_IMAGE} AS docs-build
ENV DOCS_BASE=/docs/
WORKDIR /src/docs
COPY docs/Documentation/package.json docs/Documentation/package-lock.json ./
RUN npm ci
COPY docs/Documentation ./
RUN npm run docs:check && npm run docs:build

FROM ${NODE_IMAGE} AS build
ARG VITE_PRODUCT_EDITION
ARG DOCS_VERSION
ENV VITE_PRODUCT_EDITION=${VITE_PRODUCT_EDITION}
ENV VITE_DOCS_VERSION=${DOCS_VERSION}
WORKDIR /src/web
COPY web/package.json web/package-lock.json ./
COPY version /src/version
RUN npm ci
COPY web ./
COPY --from=docs-build /src/docs/.vitepress/dist ./public/docs
RUN npm run build

FROM ${WEB_IMAGE}
COPY --from=build /src/web/dist /usr/share/nginx/html
COPY docker/runtime/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
